### ISSUE TITLE
Allow to configure which database function is called by runner.addJob 

### ISSUE THREAD

**Issue by garcianavalon** [graphile/worker#100]
## Motivation

For some use cases, users might want to create their own internal  `add_job` function that wraps `graphile_worker.add_job` to add extra logic. For example, to add entries to a historical table with all jobs for monitoring. 

These approach is fine when jobs are created through the database elements like triggers and functions, but doesn't work when jobs are created through the javascript api `runner.addJob`. Using this api will call `graphile_worker.add_job`

## Proposed solution

Graphile worker could add a configuration parameter  `addJobFunctionName` when creating the runner, that will allow to change the underlying function call from `runner.addJob`.
```js
const runner = await run({
      pgPool,
      concurrency: 5,
      pollInterval: 1000,
      taskDirectory: './tasks',
      addJobFunctionName: 'my_schema.add_job' // <-- user function
    })
```
`addJobFunctionName` should default to `graphile_worker.add_job`, making the parameter safe to add without breaking anyones code.

**Comment by benjie** [comment]
Neat idea. I think it would be better to replace the `addJob` function itself so that you may do work in JS-land too should you wish. makeAddJob is quite a simple function, so it should be fairly good to replace in your own project:

https://github.com/graphile/worker/blob/d8f9abf2c6b9503cc0d2fb5dfccbd69ed9875545/src/helpers.ts#L14-L48

We could add after line 18 something like:

```js
if (processedOptions.makeAddJob) {
  return processedOptions.makeAddJob(withPgClient, processedOptions);
}
```

**Comment by garcianavalon** [comment]
That also works 👌  

On the pros side, it gives more flexibility to the user and covers cases where `addJobFunctionName` is not enough (different signature on `my_schema.add_job`). On the drawbacks side, it makes more complex just to execute a different function. 

It is probably worth it to go for the more powerful solution, as it is a matter of time until some use case requires it. How do you think this should be implemented?

**Comment by benjie** [comment]
Not sure; I think rather than overriding the normal makeAddJob API we should let users merge their own utils into helpers. I'm not sure if this should be on a global (performant, do it once) or a per-job (costly, but much more flexible) basis. Probably global, it keeps the types really simple too.

**Comment by ben-pr-p** [comment]
I think your use case @garcianavalon is probably better accomplished via a before insert on the jobs table! In my application I have a mix of JS land `await addJob` and SQL land `graphile_worker.add_job`so I would want a solution that worked for both regardless of what my team members ended up using!

**Comment by garcianavalon** [comment]
Thanks for your suggestion @ben-pr-p Our work priorities have changed a little this pasts months, I hope I get back to Graphile-related work soon and revisit how to solve this. Reading my issue again, seems like a very complicated approach 😅

**Comment by benjie** [comment]
My preference is still to allow users to pass their own helpers, and the helpers can call whatever code they want. Thus if you have your own "my_app_add_job(...)" database function your workers can just call "helpers.myAppAddJob(...)" and all is well.

**Comment by benjie** [comment]
I'm going to close this in favour of maintaining the existing APIs
