### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ab-pm** [graphile/worker#101]
Hi,
I've just read the README and would like to ask for some clarifications/details:

* What do `run` and `makeWorkerUtils` do that requires them to return a promise (instead of the plain runner/workerutils object)? How can they fail (i.e. how should I handle errors from them)?
* "*it's often sensible to split large jobs into smaller jobs, this also allows them to run in parallel resulting in faster execution. This is particularly important for tasks that are not idempotent (i.e. running them a second time will have extra side effects) - for example sending emails.*" - How exactly would that work? I imagine that when splitting most tasks, the jobs should run sequentially. Should they be put on the same job queue then? Or should one job trigger the next one upon completion?
* When a job fails (as detailed in "*What if something goes wrong?*"), it means it is blocking the queue that it is part of?
* What exactly is the unique identifier (primary key) for a job? Is it just the `job_key`, or is it the task `identifier` plus the `job_key`?
* How do I access the id or the queue name of a job I created, if I want to reference them elsewhere (and not roll my own `sequence` to pass in explicitly, but use the implicitly generated "random" values)? I see that `addJob`/`quickAddJob` return (a promise for) a `Job`, but that type is undocumented.
* In a task executor, why should I use `withPgClient` instead of directly accessing my global singleton `PgPool` (that I also passed to `run`/`makeWorkerUtils`)? Is it really just for dependency injection?
* When using PostGraphile, and scheduling a job from within one of my custom `makeExtendSchemaPlugin` mutations, should I use the javascript `addJob` method of a `Runner`/`WorkerUtils` instance? That would presumably open a separate db connection, am I right? To schedule the job within the Postgraphile mutation transaction, I would need to call the SQL `add_job` function through the `context.pgClient`?
* Similarly, inside a task executor, do `withPgClient` and `addJob` somehow share their connection?

**Comment by benjie** [comment]
>What do run and makeWorkerUtils do that requires them to return a promise (instead of the plain runner/workerutils object)? How can they fail (i.e. how should I handle errors from them)?

Connecting to the database, running migrations, etc.

> "it's often sensible to split large jobs into smaller jobs, this also allows them to run in parallel resulting in faster execution. This is particularly important for tasks that are not idempotent (i.e. running them a second time will have extra side effects) - for example sending emails." - How exactly would that work? I imagine that when splitting most tasks, the jobs should run sequentially. Should they be put on the same job queue then? Or should one job trigger the next one upon completion?

See Graphile Starter for examples where `send_email` is called from other jobs. Both of the solutions you outline are acceptable, it depends what you're trying to achieve. For sending 10,000 emails, running them in parallel makes a lot of sense IMO, but you can serialise things as you see fit.

> When a job fails (as detailed in "What if something goes wrong?"), it means it is blocking the queue that it is part of?

Nope, just moves to the next job. We do not guarantee that jobs run in a particular order, it's "best efforts". If order is important you should make sure that later jobs are not enqueued until earlier jobs are complete.

> What exactly is the unique identifier (primary key) for a job? Is it just the job_key, or is it the task identifier plus the job_key?

https://github.com/graphile/worker/blob/d8f9abf2c6b9503cc0d2fb5dfccbd69ed9875545/sql/000001.sql#L11

`job_key` is an optional user-defined unique identifier. It is not scoped to task identifier.

> How do I access the id or the queue name of a job I created, if I want to reference them elsewhere (and not roll my own sequence to pass in explicitly, but use the implicitly generated "random" values)? I see that addJob/quickAddJob return (a promise for) a Job, but that type is undocumented.

https://github.com/graphile/worker/blob/d8f9abf2c6b9503cc0d2fb5dfccbd69ed9875545/sql/000001.sql#L11

https://github.com/graphile/worker/blob/d8f9abf2c6b9503cc0d2fb5dfccbd69ed9875545/src/interfaces.ts#L163-L164

> In a task executor, why should I use withPgClient instead of directly accessing my global singleton PgPool (that I also passed to run/makeWorkerUtils)? Is it really just for dependency injection?

It's helpful for tests because it allows you to make it use the exact same pgClient (which may be in a transaction), so that you can roll back the entire transaction when the test is done. You can do whatever you want in your task, it's just JS.

> When using PostGraphile, and scheduling a job from within one of my custom makeExtendSchemaPlugin mutations, should I use the javascript addJob method of a Runner/WorkerUtils instance? That would presumably open a separate db connection, am I right? To schedule the job within the Postgraphile mutation transaction, I would need to call the SQL add_job function through the context.pgClient?

Yes, use `WorkerUtils` because it's unlikely your PostGraphile user will have sufficient permissions to call `add_job` directly.

> Similarly, inside a task executor, do withPgClient and addJob somehow share their connection?

`addJob` uses `withPgClient` under the hood. By default `withPgClient` just grabs a client from the Pool, but you can override this in tests.

**Comment by ab-pm** [comment]
Thanks for the quick answers, it would be awesome if you could clarify these points in the readme :-)

> We do not guarantee that jobs run in a particular order, it's "best efforts".

Oh, wow. I guess I had a major misunderstanding about the term "queue" then. Also, the sentence "*Adding jobs to same named queue runs them in series*" in the *Features* section is misleading? So it's really just a concurrency limitation, "no two executions at once"?

> It's helpful for tests […] you can override [`withPgClient`] in tests.

How would you recommend to write tests? I thought about calling `await quickAddJob('to-be-tested'); await runOnce(); assertResults()`. Should I just call the function from *tasks/to-be-tested.js* and pass custom arguments that conform to the `JobHelpers` interface?

> Yes, use `WorkerUtils` because it's unlikely your PostGraphile user will have sufficient permissions to call `add_job` directly.

Oops, I had not thought about that at all. Would it be such a bad practice to grant the authenticated-user role permissions to the `graphile-worker` schema? Do I really need a separate login role?

**Comment by benjie** [comment]
> Oh, wow. I guess I had a major misunderstanding about the term "queue" then. Also, the sentence "Adding jobs to same named queue runs them in series" in the Features section is misleading? So it's really just a concurrency limitation, "no two executions at once"?

No, for tasks in a named queue it runs them in order of priority followed by run_at (which defaults to the time at which they were queued). If one fails it gets its run_at set a few seconds backwards as explained in the exponential backoff section - effectively it's sent to the back (though not strictly the "back", per-se... just a bit backwards) of the queue. I.e. it runs them in order, unless they fail, in which case they're skipped temporarily and the next job is executed.

> How would you recommend to write tests?

Have a look through the graphile-starter tests.

> Would it be such a bad practice to grant the authenticated-user role permissions to the graphile-worker schema? Do I really need a separate login role?

That's up to your application logic. Personally I do "elevated privilege" work in workers, such as sending emails, and I wouldn't want an arbitrary user being able to enqueue millions of emails being sent to random email addresses.
