### ISSUE TITLE
`process_after` sql function hook

### ISSUE THREAD

**Issue by ben-pr-p** [graphile/worker#102]
I'm proposing adding:

```
create function :GRAPHILE_WORKER_SCHEMA.add_job(
  identifier text,
  payload json = null,
  queue_name text = null,
  process_after = null,
  run_at timestamptz = null,
  max_attempts int = null,
  job_key text = null,
  priority int = null
) returns :GRAPHILE_WORKER_SCHEMA.jobs as $$
```

`process_after` (name should change to something clearer), which is an optional string reference  to a SQL function that is called after the Javascript execution and allowed to perform some work in the database (maybe queueing another job, maybe writing the result to some tables, etc.

Any such function would take one parameter - a JSON blob which is what the Javascript job returned – and either throw an error (failing the job) or have its result discarded.

This would make job re-use easier. For example, suppose in one part of my application I want hit a geocoding API and record a customer's coordinates, and in another part I want to do the same for a store. WIth `process_after`, I could do:
```
select graphile_worker.add_job('geocode', json_build_object('address', user.address), null, 'my_app.record_user_coordinates');
```
and
```
select graphile_worker.add_job('geocode', json_build_object('address', store.address), null, 'my_app.record_store_coordinates');
```
while only having one graphile-worker / Javascript job. You could imagine this making very small jobs possible, like `http-get`, `http-post`, etc.

Smaller jobs that just did the part that Postgres shouldn't do would also make testing easier, since you could call your `process_after` functions with mocks.

**Comment by ben-pr-p** [comment]
@benjie said off Github that he thinks this should be in user code (outside of the scope of this library).

I'll write a higher order function that wraps a task and calls the after hook with the result of the task, paste it here, and then close the issue!

**Comment by benjie** [comment]
I think this is a good use case for "lifecycle methods". We're still feeling out what the use-cases are for things like this, but I imagine you could have something like:

```js
const workerConfig = {
  // ...
  async onBeforeJobComplete(payload, helpers, result) {
    if (payload.process_after) {
      await helpers.withPgClient(client => client.query(`select * from ${payload.process_after}($1, $2)`, [helpers.job.id, JSON.stringify(result)]);
    }
  }
}
```

Error thrown here would be as if the job failed. Not sure about `result` - we treat tasks as void currently, but it could be the return result of the task function.

In the mean time, as you say, you can achieve this in user code by wrapping all task execution functions before handing them to graphile-worker. (This involves reading the tasks from the disk yourself, but our API allows for this.)

**Comment by ben-pr-p** [comment]
I've got a good solution of this in user code land so closing this!
