### ISSUE TITLE
Postgres does not exist error on init

### ISSUE THREAD

**Issue by joshbwlng** [graphile/worker#116]
The current try/catch logic ensures that Postgres will have the following error output at least once causing confusion for those using this library:
```
ERROR: relation "graphile_worker.migrations" does not exist at character 16
STATEMENT: select id from "graphile_worker".migrations order by id desc limit 1;
```

A simple change to the way schema existence is performed should solve this.

**Comment by benjie** [comment]
Closing - see discussion in #115
