### ISSUE TITLE
Database grinding to a halt waiting on transaction ID

### ISSUE THREAD

**Issue by mrmurphy** [graphile/worker#121]
Hey there!
We are just experimenting with migrating to Graphile Worker as our main worker driver, but it seems to have brought us down in production today, and I'm trying to find out why.

- Version: 0.6.0
- Node: 12.x
- I'm passing my existing pool from `node-postgres` when constructing `workerUtils`.
- I'm creating 5 jobs per second in one queue. Each of the 5 jobs has a consistent `jobKey`.

The idea is that these 5 jobs will run every second, unless they take longer than a second to complete, then the job will be re-queued up to one second after the previous attempt completes.

These jobs trigger a select from a table of data, and an insert into a table in another database. This shouldn't matter to the problem at hand, but both the select and the insert use their own transactions.

Sometimes this source table that the jobs are select from can build up to contain millions of rows because the database they are going to be inserted into becomes unavailable and the jobs that process them timeout. We have indexes on the table that should make it so that selecting from the table is still fast. But we've observed that when this table starts to build up, after a few hours the `add_job` graphile function starts to go insane waiting on `transactionid`:

<img width="589" alt="image" src="https://user-images.githubusercontent.com/1227109/87839472-b0e7ec80-c836-11ea-8273-5a5f56171771.png">

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/1227109/87839476-b3e2dd00-c836-11ea-84a6-a6809079e264.png">

Snapshots from RDS's dashboard^

What are the possibilities here? Am I doing something wrong with my transactions in the insertion jobs? is this an indication that I'm leaking transaction IDs? The database got so saturated that the application ground to a halt. A reboot of the Web servers didn't help. Only completely canceling the publishing of new jobs to graphile helped. When I commented out the code that published new jobs,  and restarted the servers, everything came instantly back up.

That does mean that the servers stopped _processing_ the jobs, however, so maybe our jobs are taking way too long to fail when their target DB becomes unavailable, and they're using up all available transactions / connections?

**Comment by mrmurphy** [comment]
I'm pretty sure this is an issue with how we're handling our transactions.

**Comment by Hossman333** [comment]
For what it's worth, we've tried to reproduce this issue on our own in an isolated way and could not.

Here is the gist: https://gist.github.com/Hossman333/0df575399ea7032b566ec8471ce70b22

**Comment by benjie** [comment]
This post from Tom Lane may shed some light: https://www.postgresql.org/message-id/201.1274157039%40sss.pgh.pa.us

My guess is you're doing `add_job` within a transaction, and the `on conflict (key)` clause is causing a lock, and further `add_job`s are waiting on the first transaction to commit, but you're never committing it (or you've got a large delay before committing/rolling back) causing the issues to compound.

https://github.com/graphile/worker/blob/3adcc6db925fcc73b394ff4f3585c8bad9bd2b14/sql/000004.sql#L49

`job_key` is fairly expensive, it may not be suitable for the use to which you are putting it. A better approach might be to insert a unique record into another user defined table, and then having a trigger on that create a job (without a key) to help perform any uniquing you need.

**Comment by benjie** [comment]
@mrmurphy Could you chime in here to let me know if my guess is anywhere near?

**Comment by mrmurphy** [comment]
Ah so sorry I didn't get back to you earlier. Thank you for the guess! We ended up abandoning this approach entirely for the specific feature we were working in.

**Comment by mrmurphy** [comment]
I should have closed the issue before, my apologies!
