### ISSUE TITLE
Counter for how many times a task has been debounced

### ISSUE THREAD

**Issue by lukeramsden** [graphile/worker#129]
Proposal: a counter on each job that is incremented every time it has been debounced through the job key.

My use-case is I'd like to debounce notifying the user about messages, so of course I'm using the job 
key for that, but I'd like to have the notification be "You received X new message(s)" - the ideal solution to this would just be to have a field on the job that is incremented on every debounce, and then I just pass that to my email template.

**Comment by benjie** [comment]
I can imagine a world in which I approved a "revision" or "version" counter column being added to a job. It would be updated on any change to the task identifier, queue or payload (but not run_at, attempts, last_error). Would that solve your needs?

**Comment by lukeramsden** [comment]
I believe so. I'm happy to attempt a PR for this.

**Comment by benjie** [comment]
This was implemented in #130
