### ISSUE TITLE
Cron functionality

### ISSUE THREAD

**Issue by benjie** [graphile/worker#141]
### Feature description

`cron` allows a certain task to be executed periodically (e.g. daily, hourly, 4am on Thursdays, etc). We could add support for this in Graphile Worker since many users will require this functionality.

### Motivating examples

- Scheduling a weekly summary email every Monday
- Clearing stale data from the database
- Database maintenance (e.g. VACUUM)

### Breaking changes

None.

### Supporting development

I [tick all that apply]:

- [x] am interested in building this feature myself
- [x] am interested in collaborating on building this feature
- [x] am willing to help testing this feature before it's released
- [x] am willing to write a test-driven test suite for this feature (before it exists)
- [x] am the maintainer ;)

**Comment by benjie** [comment]
It's fairly easy to emulate cron functionality currently. One way is to have a table in the DB that has a trigger which queues a job:

```sql
create table cron (
  period text,
  identifier text,
  primary key(period, identifier)
);

create function tg_cron__trigger() returns trigger as $$
begin
  perform graphile_worker.add_job('cron', json_build_object('period', NEW.period, 'identifier', NEW.identifier));
  return NEW;
end;
$$ language plpgsql volatile;

create trigger _500_cron after insert on cron for each row execute procedure tg_cron__trigger();
```

Then you create a loop somewhere (your worker, your server, somewhere else, it doesn't really matter) and have that do something like:

```ts
let lastDate = null;
setInterval(() => {
  const now = new Date();
  const yyyy = now.getISOFullYear();
  const mm = now.getISOMonth() + 1;
  const dd = now.getISODate();
  const date = `${yyyy}-${mm}-${dd}`;
  if (date !== lastDate) {
    // Only talk to the DB when necessary
    lastDate = date;
    db.query('insert into cron (period, identifier) values ($1, $2)', ['daily', date]);
  }
}, 60000);
```

You can make this a bit smarter so that it's closer to hitting the actual time (e.g. do you really need setInterval, or should you setTimeout to the next timestamp you're expecting a date change to occur on?)

Using the table ensures that you can't trigger the same cron twice.

**Comment by benjie** [comment]
A task that used the above could run every Monday at 4am with a `cron` task like:

```ts
const task = (payload) => {
  const { period, identifier } = payload;
  const d = new Date(identifier);
  if (period === 'hourly') {
    if (d.getUTCDay() === 1 && d.getUTCHour() === 4) {
      // It's 4am on a Monday, do something.
    }
  }
}
```

**Comment by lukeramsden** [comment]
Interesting, as this is something I'm just about to need for my project. My initial plan was to have the task schedule itself, i.e. on a certain trigger (in my case, a user action) schedule a task with that users ID in its params and job key for midnight, and then when the task is completed it schedules itself for the next midnight, and again and again. There will also actually be two different tasks, with Sundays having a different task scheduled for an earlier time.
How do you think this compares to your implementation with the loop? Now I've seen this issue I'm reconsidering my design for how to achieve my use-case.

My ideal implementation would be a function along the lines of a `graphile_worker.add_cron` (and a companion `remove_cron` function) function which takes a `job_key`-like identifier, along with all the other job params like priority etc, and also a cron expression. Then graphile-worker will schedule jobs with those params accordingly. Not sure if this is quite what you're thinking.

**Comment by joelmukuthu** [comment]
@benjie just drawing your attention to this project https://github.com/davbeck/graphile-scheduler in case you haven't seen it. I haven't tried it nor have I looked though its implementation, just thought it might be worth looking at for you :)

**Comment by benjie** [comment]
I totally forgot about that, thanks for reminding me! @davbeck What do you think about working together to merge this feature into core? There's sufficient interest to justify it, I think.

In the mean time please feel free to send a PR to the README linking out to your project :+1:

**Comment by davbeck** [comment]
I would love to. I think the code bases would integrate pretty cleanly. I should have some time next week to submit an initial PR merging the projects next week.

**Comment by benjie** [comment]
Awesome! 🙌 I suspect there’ll be a bit of back and forth before we merge, but a clean PR would be an excellent start 🚀

**Comment by josephxanderson** [comment]
@benjie @davbeck What's the status of this? I would love to see it moved into the graphite-worker package to help ensure it's maintained.

**Comment by davbeck** [comment]
I got it started but then got busy. Still hope to get it merged in.

**Comment by benjie** [comment]
I spent some more time looking at Graphile Scheduler's internals and I think its goals are a bit different from the goals that I have in mind for cron functionality in Graphile Worker. There's definitely overlap, but I'd rather keep a very lean core that projects like Graphile Scheduler can build on top of. In particular, I don't want to support the schedules being managed by a database table. For me, the performance of this feature _in core_ is critical so I don't want people to start scheduling repeating tasks on a per-user basis such that there are thousands of schedules. There's a few other architectural trade-offs where I swing a different way to Graphile Scheduler (for example I have no intention of supporting timezones, I don't want to add dependencies for date manipulation, tasks should not (be able to) be defined inline, and really I want more of a `crontab`-style experience). I'm working on a solution that I hope Graphile Scheduler might be able to leverage.

**Comment by benjie** [comment]
WIP implementation here: https://github.com/graphile/worker/blob/8dfac3ad330abf7cd56c72defe5e4f6c25571c17/README.md#recurring-tasks-crontab


Needs tests before it can be merged; feedback welcome.

**Comment by davbeck** [comment]
Interesting. So you're still tracking the schedules in the database, but just their last execution state. The actual schedule is provided in configuration.

For whatever it's worth, I think this will work. Supporting a large number of schedules was just a side effect of my design. What I was really aiming for was resilience in regards to downtime and deployment, which I'm pretty sure this approach accomplishes just as well.

It looks like backfill is off by default, which I also support. The original project I was working on when I built scheduler required that every scheduled event was executed no matter what, but since then every project I've worked on with scheduling, and thinking back on other projects I've used scheduling with, that isn't actually the case.

Speaking of backfill, the documentation says that `fill` is a time phrase, but the example just has `1` and says that will back fill 1 task rather than a previous timespan.

**Comment by benjie** [comment]
Thanks for the feedback @davbeck :+1: 

> So you're still tracking the schedules in the database, but just their last execution state. The actual schedule is provided in configuration.

Yeah; the execution date is just to give us a distributed lock effectively. I designed it this way so the table wouldn't grow over time, keeping it small and extremely efficient I hope :+1: 

> Supporting a large number of schedules was just a side effect of my design. 

Ah; fair enough! It was a side effect I decided I did not want to support (both in terms of providing the functionality, and in terms of dealing with the inevitable GitHub issues filed about it :wink:), but I'm glad that it's still useful for you without this. I was thinking that a schedule table could still be supported using an alternative form of watch mode, but if you don't need this I won't invest the time in writing it up :laughing: 

> The original project I was working on when I built scheduler required that every scheduled event was executed no matter what, but since then every project I've worked on with scheduling, and thinking back on other projects I've used scheduling with, that isn't actually the case.

Agreed. Data rollups need it, for example, but I'd say most cron-like jobs don't, at least not much.

> Speaking of backfill, the documentation says that fill is a time phrase, but the example just has 1 and says that will back fill 1 task rather than a previous timespan.

Oops; yeah I changed it from a count of backfills (which turned out to be unnecessarily complex to implement), clearly forgot to update that part of the README!

**Comment by benjie** [comment]
Implemented in #163

**Comment by joelmukuthu** [comment]
@benjie regarding the implementation in #163, as opposed to running a single app, could one run two separate apps where one processes recurring jobs while the other processes regular jobs?  Also, are there database dependencies between them or could the apps be configured to use different schemas on postgres?

**Comment by benjie** [comment]
Yes, each worker only runs the tasks it understands; you can run separate workers if you like. Yes they can use different schemas if required.
