### ISSUE TITLE
Why does sigpipe trigger a shutdown?

### ISSUE THREAD

**Issue by ibash** [graphile/worker#159]
### Summary

By default SIGPIPE is triggers a graceful shutdown: https://github.com/graphile/worker/blob/main/src/signals.ts#L5
I looked through the commit history but couldn't see why.

### Additional context

Currently I'm using a worker in the same service as my web service. SIGPIPE was causing a shutdown but I think it was a signal unrelated to graphile worker. Is it there for any specific reason?

**Comment by benjie** [comment]
> SIGPIPE is the "broken pipe" signal, which is sent to a process when it attempts to write to a pipe whose read end has closed (or when it attempts to write to a socket that is no longer open for reading), but not vice versa. **The default action is to terminate the process.**

Worker by default catches all signals it can that would cause process termination, and instead does graceful process shutdown. You can, however, opt out of signal handling and do it yourself if your needs are different from the norm 👍

**Comment by ibash** [comment]
Thanks!

**Comment by benjie** [comment]
Revisited this, and decided to not handle SIGPIPE: https://github.com/graphile/worker/pull/179
