### ISSUE TITLE
pg-boss vs graphile-worker?

### ISSUE THREAD

**Issue by stephane-klein** [graphile/worker#173]
Hi,

I have just seen [pg-boss](https://github.com/timgit/pg-boss) project from [Postgres Weekly](https://postgresweekly.com/) email.

I'm a [graphile / worker](https://github.com/graphile/worker) and I wonder what are difference between **pg-boss** and [graphile-worker](https://github.com/graphile/worker).

This two projects achieve the same goals?

Same question on [pg-boss issues](https://github.com/timgit/pg-boss/issues/227)

Best regards,
Stéphane

**Comment by benjie** [comment]
I've not used pg-boss so can't say for certain; but I'd hazard that though the two projects can likely be used to solve similar goals, the main difference is probably that Graphile Worker has a Postgres-centric API (with JS bindings), whereas pg-boss has a JS-centric API. They also have various different design decisions - how the worker is started, how jobs are structured, queued, executed, etc - but outlining the differences there would be a significant undertaking.
