### ISSUE TITLE
Job History

### ISSUE THREAD

**Issue by mikeburgh** [graphile/worker#174]
### Feature description

A way to preserve completed jobs, their payload, the dates around when they were queued and completed, and any retry counts. 

They could then be purged from the history at some future timeframe.

### Motivating example

Being able to run stats as well as look at the history for particular job types, there is also a potential for forensic needs when investigating to be able to see what happened. 

I realize at the moment if the job is not in the job table it's been completed, but sometimes you need data to back that up.

### Ideas on implementing

I think the simplest would be a trigger on the jobs table to write the deleted records into another table. Those rows could then be deleted from the other table after a definable period. 

The complexity creeps in when you may not care to have all jobs saved in history, or perhaps saved for different periods of time and how you go about pruning that table.

I had the thought that you could let the addJob calls set the history value and use that to calculate a purge after date when adding to the history table, or maybe it's an exported value from task files if you did want to start getting into letting tasks set their own retention timeframes vs per job.

I have not dug too far into this yet, as I was interested in hearing your thoughts on it, and how you would like to see something like this implemented ?

### Supporting development

I :
- [ x] am interested in building this feature myself
- [ x] am interested in collaborating on building this feature
- [x ] am willing to help testing this feature before it's released
- [ ] am willing to write a test-driven test suite for this feature (before it exists)
- [ ] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by benjie** [comment]
This kind of feature would have a significant impact on Worker’s performance, and for that reason I do not want to support it in core.

That said, it’s relatively easy for you to set this up in your own DB by installing triggers against the jobs table; I recommend using the row_to_json function so that your code will automatically reflect changes to the worker API.

**Comment by mikeburgh** [comment]
Thanks for the feedback, do you see the performance impact from the implementation of a trigger ? or just the overhead in writing a new row in general ? 
Other thought I had was to do it via the events you added recently, I need to dig into those to see if there would be enough data in them. Either way I will look to do it as a standalone that people can use if they want.

**Comment by benjie** [comment]
Both of those things; performance is a feature of Graphile Worker so I’m not willing to compromise on it unless there’s a really good reason. But assuming you don’t need the absolute highest performance you’ll probably be fine.

Using events would probably work, but there’s a risk of data loss as they don’t have the transactional safety.

**Comment by joeyorlando** [comment]
For anyone else coming across this thread. @benjie proposed a solution on Discord [here](https://discord.com/channels/489127045289476126/498852330754801666/938957554753605743)

**Comment by benjie** [comment]
Closing this issue as it is not something that I want to add to Graphile Worker.

**Comment by jukkasi** [comment]
For others looking for a solution, what was proposed in Discord was something like

`create table log (
  job_id int primary key,
  record json
);
create function tg_log() returns trigger as $$
begin
  insert into log(job_id, record) values (OLD.id, row_to_json(OLD));
  return NULL;
end;
$$ language plpgsql;
create trigger _500_log after delete on graphile_worker.jobs for each row execute procedure tg_log();
`

While performance concerns are a valid point for production use, there might be other use cases like testing where tracking jobs might be useful.
