### ISSUE TITLE
Find the last time a cron job was ran

### ISSUE THREAD

**Issue by wokalski** [graphile/worker#177]
## cron

I am setting a backfill period which makes sense for my application but additionally I'd like to set an alarm if the last execution of my cron was more than 3 days (my backfill period is 2 days). Is it possible yet?

**Comment by benjie** [comment]
Have a look at this event:

https://github.com/graphile/worker/blob/main/src/interfaces.ts#L640

if that doesn’t do what you need, a PR to add the required additional piece of data so it does would be welcome 👍

**Comment by wokalski** [comment]
I ended up not implementing this functionality in my app after all but having these two pieces of information would be really helpful anyway:

https://github.com/graphile/worker/blob/e3176eab42ada8f4f3718192bada776c22946583/src/interfaces.ts#L279-L280
