### ISSUE TITLE
Runner shuts down the express server when disconnected from database

### ISSUE THREAD

**Issue by Siva-R** [graphile/worker#178]
I am using node-express and configured graphile-worker(0.9.0)  with simple runner as below. However, when runner gets disconnected with database and after sometime (5-10 minutes) it brings down the express server with uncaughtException: read ETIMEDOUT at TCP.onStreamRead(internal/stream_base_commons.js:209:20) . 

The pgPool.on('error') is also not getting triggered.

```js
async function main() {
  // Run a worker to execute jobs:
  const runner = await run({
    connectionString: "postgres:///my_db",
    concurrency: 5,
    // Install signal handlers for graceful shutdown on SIGINT, SIGTERM, etc
    noHandleSignals: false,
    pollInterval: 1000,
    // you can set the taskList or taskDirectory but not both
    taskList: {
      hello: async (payload, helpers) => {
        const { name } = payload;
        helpers.logger.info(`Hello, ${name}`);
      },
    },
    // or:
    //   taskDirectory: `${__dirname}/tasks`,
  });
  await runner.promise;
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
```

**Comment by benjie** [comment]
I could not reproduce this; however I could make it give me unhandled promise rejection errors, so I've raised this: https://github.com/graphile/worker/pull/179

**Comment by Siva-R** [comment]
Thanks Benjie. Can we expect the changes to be merged today?

**Comment by benjie** [comment]
No

**Comment by benjie** [comment]
This is out in `graphile-worker@next` - let me know if it fixes your issues :+1:

**Comment by Siva-R** [comment]
I dowloaded graphile-worker - ^0.10.0 on my mac and this is what I see after 5 minutes getting disconnected from database. The server gets shutdown eventually

events.js:292
      throw er; // Unhandled 'error' event
      ^
Error: read EHOSTUNREACH
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
Emitted 'error' event on Client instance at:
    at Client._handleErrorEvent (/Users/xyz/research/abc/node_modules/pg/lib/client.js:319:10)
    at Connection.emit (events.js:315:20)
    at Socket.reportStreamError (/Users/xyz/research/abc/node_modules/pg/lib/connection.js:53:12)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -65,
  code: 'EHOSTUNREACH',
  syscall: 'read'
}

**Comment by benjie** [comment]
Can you share your code or how you’re running it?

**Comment by benjie** [comment]
Maybe it’s one of your tasks causing it.

**Comment by Siva-R** [comment]
const express = require('express')
const app = express();
const http = require('http')
const {run} = require('graphile-worker')

async function main() {
  // Run a worker to execute jobs:
  const runner = await run({
    connectionString: "postgres:///my_db",
    concurrency: 5,
    // Install signal handlers for graceful shutdown on SIGINT, SIGTERM, etc
    noHandleSignals: false,
    pollInterval: 1000,
    // you can set the taskList or taskDirectory but not both
    taskList: {
      hello: async (payload, helpers) => {
        const { name } = payload;
        helpers.logger.info(`Hello, ${name}`);
      },
    },
  });


  await runner.promise;
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});

const port = 3000;
const server = http.createServer(app)
server.listen(port).on('listening', onListening)

// for ctrl-c
process.on('SIGINT', function() {
    console.log('Due to ctrl-c')
    server.close();
    process.exit();
})

function onListening(){
    console.log('App listening on port ', port);
}

**Comment by Siva-R** [comment]
Hi Benjie, any update on the above issue?

**Comment by benjie** [comment]
I cannot reproduce this issue. Please file a full reproduction.

**Comment by Siva-R** [comment]
Hi Benjie, I am able to isolate the issue . Below are the steps to reproduce the issue
1) Make sure that you are using remote database
2) Run that above code and ensure that graphile worker is connected to this remote database successfully
3) Now turn off the network by turning off the WIFI or network cable.
4) Give it 10 minutes and you will see the below error brining the entire server down. It will be either ETIMEDOUT or EHOSTUNREACH error.

events.js:292
throw er; // Unhandled 'error' event
^
Error: read ETIMEDOUT
at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
Emitted 'error' event on Client instance at:
at Client._handleErrorEvent (/Users/xyz/research/abc/node_modules/pg/lib/client.js:319:10)
at Connection.emit (events.js:315:20)
at Socket.reportStreamError (/Users/xyz/research/abc/node_modules/pg/lib/connection.js:53:12)
at Socket.emit (events.js:315:20)
at emitErrorNT (internal/streams/destroy.js:106:8)
at emitErrorCloseNT (internal/streams/destroy.js:74:3)
at processTicksAndRejections (internal/process/task_queues.js:80:21) {
errno: -60,
code: 'ETIMEDOUT',
syscall: 'read'
}

**Comment by Siva-R** [comment]
Hi Benjie, Following up on this, did you get a chance to look into this?

**Comment by benjie** [comment]
Not yet; it's still marked unread in my GitHub notifications inbox. I went to try and reproduce it on my laptop the other day but the battery was dead :man_facepalming: and since then I've had other focuses.

Have you tried reproducing the issue with vanilla `pg` module? It might turn out to be a bug in that.

**Comment by benjie** [comment]
(I say this because you state the `.on('error')` is not called.)

**Comment by Siva-R** [comment]
Alright, I think I have some information for you. I have printed the postgres client object which is emitting  the above ETIMEDOUT error, and below is what it look like . If you look at the sql statement in bold, it looks like it is getting executed by worker and it seems like the worker client is missing the 'error' event handler and that is causing the server to stop. Hope this info will help you in fixing this issue.

Client {
 ....
 ....
 user: 'abcd',
 database: 'xyx',
 host:'myhost.com'
 connection: Connection {
   .....
   .....
   parsedStatements: {
    **'get_job/graphile_worker': 'SELECT * FROM "graphile_worker".get_job($1, $2 , forbidden_flags := $3::text[]);'**
  }
  }
}

**Comment by benjie** [comment]
Please go into your `node_modules` and edit `graphile-worker/dist/lib.js`; you should find code that looks something like:

```ts
  pgPool.on("error", handlePoolError);
  releasers.push(() => {
    pgPool.removeListener("error", handlePoolError);
  });
```

Please change it to:

```js
  pgPool.on("error", handlePoolError);
  const handleClientError = (client) => client.on('error', handlePoolError);
  pgPool.on("connect", handleClientError);
  releasers.push(() => {
    pgPool.removeListener("error", handlePoolError);
    pgPool.removeListener("connect", handleClientError);
  });
```

and see if that fixes the issue.

**Comment by Siva-R** [comment]
Thanks, the fix worked. I will wait for this to make it to master and will pick the new version.

**Comment by Siva-R** [comment]
Hi, I am somehow unable to checkout the 0.11.1 version, is the code merged?

**Comment by benjie** [comment]
Released now :+1:
