### ISSUE TITLE
permission denied for schema public while running worker

### ISSUE THREAD

**Issue by wokalski** [graphile/worker#199]
### Summary

In my specific database setup I get `permission denied for schema public` when I try to run graphite worker. It stems from `public.gen_random_uuid`.

### Steps to reproduce

Create a user without permissions to public schema.

### Expected results

This is documented and the error is better.

### Actual results

The error is cryptic.

**Comment by benjie** [comment]
Graphile Worker no longer uses `gen_random_uuid()`
