### ISSUE TITLE
Add way to set flags for Cron jobs

### ISSUE THREAD

**Issue by rpaterson** [graphile/worker#202]
### Feature description

It's possible to set a job's `flags` property from the `addJob()` function in Node and from the `add_job()` function in SQL, but not when it's scheduled using the Cron functionality. Add a way to specify flags for Cron jobs, both in the `crontab` file and in `CronItem`.

### Motivating example

I'm using `forbiddenFlags` to control which jobs worker runs, and I want to be able to use it with Cron jobs as well.

### Breaking changes

Should be additive.

### Supporting development

I [tick all that apply]:

- [ ] am interested in building this feature myself
- [ ] am interested in collaborating on building this feature
- [ ] am willing to help testing this feature before it's released
- [ ] am willing to write a test-driven test suite for this feature (before it exists)
- [ ] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by rpaterson** [comment]
On second thought maybe flags aren't appropriate for Cron jobs anyway.

**Comment by benjie** [comment]
Effectively we'd just add more ?opts to add them, so if you had a compelling reason I'd certainly review a PR :+1:
