### ISSUE TITLE
Add ability to override the schema in which extensions are installed

### ISSUE THREAD

**Issue by jcgsville** [graphile/worker#208]
### Feature description

I'd like the ability to control via some mechanism which schema the pgcrypto schema is attempted to be installed into. Today, it is only installed into `public`.

https://github.com/graphile/worker/blob/e3176eab42ada8f4f3718192bada776c22946583/src/migrate.ts

It makes no difference to me if this is an environment variable or cli flag/library option.

### Motivating example

For my graphile-based project, I went down the path of removing the public schema entirely from my DB. I installed all extensions into an `extensions` schema and put only this schema on the search path. While it's not necessarily typical, some quick googling suggests that I'm not the only one who has taken this approach, so it seems reasonable that graphile worker should support this.

### Breaking changes

This should not involve breaking changes, the default schema would remain `public`

### Supporting development

I [tick all that apply]:

- [x] am interested in building this feature myself
(I'm not chomping at the bit to take this on, but I'm willing to do it to get off my fork 😄 )
- [x] am interested in collaborating on building this feature
- [x] am willing to help testing this feature before it's released
- [ ] am willing to write a test-driven test suite for this feature (before it exists)
- [ ] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by jcgsville** [comment]
I did a little bit of digging here, and it looks like this change would require not just updating migrate.ts, but also the migration SQL files. Is that something we're open to doing? Or are migrations append-only?

In reading through migrate.ts, it seems like it should be fine and wouldn't affect anyone who's run the migration already, but there could be something I'm missing there.

**Comment by benjie** [comment]
We already use `:GRAPHILE_WORKER_SCHEMA` in the migrations to changing `public.gen_random_uuid` to `:PG_CRYPTO_SCHEMA.gen_random_uuid` seems reasonable. You can do that to pre-existing migrations, they're not signed or anything like that :eyes: :grin:

**Comment by jcgsville** [comment]
Closing in favor of #251
