### ISSUE TITLE
Running cron in a distributed environment

### ISSUE THREAD

**Issue by wokalski** [graphile/worker#211]
What if I have two instances of my applications using cron in library mode with different cron patterns for each? What happens if I remove a task from one but keep it in the other (purely hypothetical but I'm trying to understand the mechanics).

**Comment by benjie** [comment]
That’s fine so long as you specify unique cron identifiers. It’s also fine (and, indeed, desirable) to have multiple nodes running the same cron schedules with the same cron identifiers - whoever’s first will schedule the task and the latter will no-op (we manage this with a tracking table for cron ids/timestamps). What you should avoid is multiple nodes using the same cron identifiers for different schedules, though technically this will work too - it’ll fire, I think, for every matching timestamp across both instances (like a union), but will not trigger for the same timestamp twice even if the schedules use different task identifiers/payloads/etc.

**Comment by wokalski** [comment]
I see, thank you. It'd be cool to see that documented. It gives some intuition as to how cron works here. It allows me to infer (together with what I saw in the database) that the database stores last execution but there's no db logic to schedule triggers from the DB. graphile-worker does some sort of polling and fires when the pattern matches. Thank you.

**Comment by benjie** [comment]
https://github.com/graphile/worker/pull/214
