### ISSUE TITLE
Add a method to do what Graphile worker does on `SIGTERM` manually

### ISSUE THREAD

**Issue by ben-pr-p** [graphile/worker#229]
### Feature description

Add a method on `worker` (maybe `.fastCleanup()` or `.stop({ fast: true })`) that does what Graphile worker does on `SIGTERM` (fail all running jobs and exit), versus `.stop()`, which waits for all running jobs to complete.

### Motivating example

We use https://github.com/gajus/lightship to manage startup and cleanup of our NodeJS pods, and having the fast exit as a option when controlling things ourselves would be useful. Right now, we intercept SIGTERM and so the default behavior is not available to us.

See https://github.com/graphile/worker/issues/222#issuecomment-926627835

### Supporting development

I [tick all that apply]:

- [ ] am interested in building this feature myself
- [x] am interested in collaborating on building this feature
- [ ] am willing to help testing this feature before it's released
- [ ] am willing to write a test-driven test suite for this feature (before it exists)
- [x] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by benjie** [comment]
As of 0.16.0, calling `runner.stop()` should now perform the graceful shutdown method, the same as SIGTERM/etc do. Related: #353
