### ISSUE TITLE
Resolve runner.stop() after all event listeners is resolved

### ISSUE THREAD

**Issue by countcain** [graphile/worker#236]
### Feature description

Is it possible to wait for the execution of all event listeners before completing the graceful shutdown for the runner?

### Motivating example

For example, I want to do some job cleaning stuff or post job processing actions in the `job:success` or `job:error` event listeners.
The current behavior of `runner.stop()` is it shutdowns all workers and become resolved. I hope it becomes resolved only after all listeners are resolved.

### Breaking changes

I don't think so.

### Supporting development

I [tick all that apply]:

- [x] am interested in building this feature myself
- [x] am interested in collaborating on building this feature
- [x] am willing to help testing this feature before it's released
- [ ] am willing to write a test-driven test suite for this feature (before it exists)
- [ ] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by benjie** [comment]
No; `EventEmitter` does not "listen" to the result of the event handlers so we cannot retrieve/await them.

An alternative approach would be to add explicit shutdown hooks (e.g. an `onStop` callback) that's separate from the EventEmitter-based events system.

If you're triggering a graceful shutdown manually then you can call the events after `stop()`. If the graceful shutdown is in response to an event then the absolute minimum amount of work possible should be done to allow the process to exit as soon as possible after the exit was requested.
