### ISSUE TITLE
Crash with esbuild

### ISSUE THREAD

**Issue by IlyaSemenov** [graphile/worker#246]
### Summary

When graphile-worker is started in an esbuild-compiled bundle, it crashes.

### Steps to reproduce

Create `test.js`:

```js
const { run } = require("graphile-worker")

async function main() {
	await run({ connectionString: "postgres:///my_db" })
}

main()
```

Create the db, then run:

```
yarn add graphile-worker esbuild
yarn esbuild test.js --bundle --platform=node --outfile=test-out.js --external:pg-native --external:pg-query-stream --external:fsevents && node test-out.js
```

### Expected results

The app runs normally.

### Actual results

```
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: ENOENT: no such file or directory, scandir '/Users/semenov/tmp/graphile-esbuild/../sql'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/Users/semenov/tmp/graphile-esbuild/../sql'
}
```

### Additional context

node 16.13.0
PostgreSQL 14.0

### Possible Solution

I believe the SQL files should be somehow inlined during graphile-worker's own build step, so that the resulting `node_modules/graphile-worker` that is distributed is a plain javascript module not trying to read its own source code.

As a temporary hack, something like `GRAPHILE_WORKER_SQL` environment variable could be introduced allowing users to override `${__dirname}/../sql`.

### Side notes

Unconditional dependency on `fsevents` (or rather `chokidar`) should also be removed. It's not needed in production.

**Comment by benjie** [comment]
SQL files have now been converted to JS in #345, so this should no longer be an issue.
