### ISSUE TITLE
pgcrypto not necessary in PostgreSQL 13+?

### ISSUE THREAD

**Issue by noinkling** [graphile/worker#249]
Correct me if I'm wrong, but pgcrypto only appears to be installed in order to use `gen_random_uuid()`. That function [is available without the extension](https://www.postgresql.org/docs/current/functions-uuid.html) in Postgres 13+. Is it feasible to make the installation of pgcrypto conditional on version so it can be avoided if unnecessary?

**Comment by benjie** [comment]
Seems like a reasonable suggestion; here's the relevant line if you fancy sending a PR: https://github.com/graphile/worker/blob/e3176eab42ada8f4f3718192bada776c22946583/src/migrate.ts#L10

**Comment by benjie** [comment]
To be honest, we could just remove that line and state in the README that if you want to use < PG13 you'll need to install the `pgcrypto` extension :man_shrugging:

**Comment by noinkling** [comment]
I won't offer any input on that decision since it wouldn't affect me personally, other than to say it sounds like a better idea in the long term.

Either way, currently `gen_random_uuid()` calls are qualified with the `public` schema, whereas the built-in version is on `pg_catalog`. Is it OK to unqualify it and just implicitly rely on the `search_path` in older versions?

Alternatively I guess you could create a proxy function in the graphile-worker schema that simply delegates to the appropriate one.

**Comment by benjie** [comment]
Removing the qualification sounds acceptable.
