### ISSUE TITLE
RLS on worker tables

### ISSUE THREAD

**Issue by madflow** [graphile/worker#25]
The current schema migration creates tables with RLS enabled and no policies. This means that only the table owner is able to enqueue jobs.

This means, that I have to start the worker with a specific owner that will enqueue the jobs later, who can create a schema and tables.

But - In an application environment where different database roles a crucial (Postgraphile, Postgrest) I would not be able to enqueue jobs with any other user than the table owner (except with a Security Definer).

Since there are now policies anyway - I would suggest to drop them from the tables.

Or... I am missing something here...?

**Comment by benjie** [comment]
I prefer to enable RLS on all tables as a best practice. Is RLS being enabled causing you issues?

**Comment by madflow** [comment]
I use Postgraphile. 

* The connection is made by an `adminuser` that can create tables and owns tables etc.
* The same `adminuser` is used for the `worker` connection.
* A request made to the Graphql endpoint sends `jwt.claims.role = webuser `. 
* When I try to enqueue a job with graphile_worker.addJob in a context where the current role is set to `webuser` - the insert on the jobs table fails - because only `adminuser` as the table owner of `jobs` can do that.

This is the issue I am facing. I agree that RLS is good practice - but RLS without any policies could also be manager by the usual "granted" rights on a table I would argue.

I am open for suggestions what a good pattern to enqueue jobs without being the table owner are, though ;)

**Comment by benjie** [comment]
Aside: I would not recommend using `adminuser` as the PostGraphile user; you should use a lower privileged role, such as [this one from the bootstrap setup script](https://github.com/graphile/bootstrap-react-apollo/blob/36d06ba04c66878bf649bf234001f8ffb446d49c/scripts/setup#L158-L164).

I use `SECURITY DEFINER` functions to enqueue jobs, and this is what I'd advise currently.

I don't think the issues you raise would be solved by removing the RLS on those tables. Granting rights unilaterally to the table is likely to open your system to security issues, if you grant rights you should also create policies that govern those rights, otherwise someone could insert/delete/read a job that affects a different user ─ this is why RLS is enabled on these tables as a second layer of defence over RBAC alone (which may be compromised via `ALTER DEFAULT PRIVILEGES`).

**Comment by madflow** [comment]
> Aside: I would not recommend using adminuser as the PostGraphile user; you should use a lower privileged role, such as this one from the bootstrap setup script.

The "default user" is a lower privileged role. The connection (pg pool) is made by the database owner just like in the bootstrap project. I'll look into the migrations there for more inspiration, thanks.

In the meantime I already settled for security definer functions. I wanted to have statistics for all jobs so I created a jobs table with a `job_state` and a `user_id` column which delegates the jobs with a trigger to the `graphile_worker.jobs`  table. There I have RLS polices (due to the user_id column) which make sense for my use case. This is in an experimental stage - so not sure yet if this is a good idea after all.

More security is great. It is still weird to me, that the database role that can insert jobs is the one, that firstly created the schema on the first start. I somewhat would applaud more control over this but lack experience with PG job queues. So closing for now, thanks!

**Comment by benjie** [comment]
> I wanted to have statistics for all jobs so I created a jobs table with a `job_state` and a `user_id` column which delegates the jobs with a trigger to the `graphile_worker.jobs` table. There I have RLS polices (due to the user_id column) which make sense for my use case. This is in an experimental stage - so not sure yet if this is a good idea after all.

I've been considering adding something like this into graphile-worker directly, I've not yet come up with a solution that I see working for all people, but I'd definitely be interested to hear what you figure out - what works and what doesn't.

> It is still weird to me, that the database role that can insert jobs is the one, that firstly created the schema on the first start. 

I've not come up with a clean solution for using different privileges; in future I think different tasks may use different roles/settings, but we've not advanced the project that far yet. If you come up with concrete proposals for this, I'd love to hear them :+1: 

> The "default user" is a lower privileged role. The connection (pg pool) is made by the database owner just like in the bootstrap project. I'll look into the migrations there for more inspiration, thanks.

The bootstrap project does not use the database owner in the pool that PostGraphile uses, it [uses `authPgPool`](https://github.com/graphile/bootstrap-react-apollo/blob/36d06ba04c66878bf649bf234001f8ffb446d49c/server/middleware/installPostGraphile.js#L227) which [uses AUTH_DATABASE_URL](https://github.com/graphile/bootstrap-react-apollo/blob/36d06ba04c66878bf649bf234001f8ffb446d49c/server/middleware/installDatabasePools.js#L12) which [uses](https://github.com/graphile/bootstrap-react-apollo/blob/36d06ba04c66878bf649bf234001f8ffb446d49c/scripts/setup#L78) the [unprivileged DATABASE_AUTHENTICATOR role](https://github.com/graphile/bootstrap-react-apollo/blob/36d06ba04c66878bf649bf234001f8ffb446d49c/scripts/setup#L60-L63). This is just an additional layer of security, in case a vulnerability is found in PostGraphile or one of the libraries it depends on, I'm not aware of any issues of using the database owner role directly, I just have an abundance of caution :)

> So closing for now, thanks!

Thanks, and thanks for the feedback :+1:

**Comment by keithlayne** [comment]
Sorry for digging up closed issues lately, but had the same kind of questions.  Notably, in https://github.com/graphile/bootstrap-react-apollo/blob/master/db/migrations/20181102_200855.app_private.tables.user_email_secrets-up.sql#L32-L42 the function is not created with `security definer`.  I'm guessing this is an artifact of how that project developed, but i.e. `add_job` in the current version of this project doesn't use that either.  Haven't tried it yet, but I'm assuming that will break.

I'm going to go ahead and mark my job-enqueueing (is that a word?) functions as `security definer` for now unless I'm missing something.

**Comment by benjie** [comment]
Yeah; that'll probably break - if you wanted to raise a PR against bootstrap to fix it I'd appreciate it. I'm focussed on the new starter project (not yet published) so I'm not working on bootstrap and it seems that some recent PRs have broken it without my realising :disappointed: 

Functions that enqueue jobs should be security definer :+1:
