### ISSUE TITLE
Crontab runs tasks 6 hours later than defined

### ISSUE THREAD

**Issue by Hagalas** [graphile/worker#252]
### Summary

My crontab looks like this:
`0 9 * * 2 taskExample` but job runs 6 hours later (at 3pm). 
I checked time on remote machine where the app is running. Same with docker container and database. They all show correct time. 
Any suggestions?

**Comment by benjie** [comment]
What timezone is your system set to? Try setting it to UTC.

**Comment by benjie** [comment]
Actually that should make no difference, we only run using UTC times no matter the system timezone I think. At least that’s what the README says 🤷‍♂️

**Comment by benjie** [comment]
I'm going to assume this was a timezone issue. Relevant: #334
