### ISSUE TITLE
Checking health of the worker

### ISSUE THREAD

**Issue by wokalski** [graphile/worker#253]
Yesterday we've experienced some sort of deadlock of the worker. There are no logs, nothing so we can't really say what it was but it's clear that the  worker hang. Do you have any ideas or techniques for worker health checks? I'm thinking about adding a recurring task but it doesn't really make sense because you want to make sure that the worker is healthy on per-worker basis (in case one has multiple instances).

**Comment by benjie** [comment]
Here's a few thoughts on why a worker might hang:

1. the pg clients never return responses to queries (e.g. you're using a DB pool and connections never become free so they just hang indefinitely)
2. one of your tasks enters an infinite loop so Node can't process anything else

I can't think of any more off the top of my head.

These have different symptoms. For 2, adding a webserver that just serves "OK" to the same Node process would be sufficient - if there's an infinite loop then the webserver cannot reply -> unhealthly. For 1, this'll be much harder to detect. Have a look at our event hooks and see if you can come up with a useful heuristic from them?

**Comment by wokalski** [comment]
The event hooks indeed make sense. Thanks!!
