### ISSUE TITLE
cron promise is ignored in the main runloop causing uncaught exceptions (!!!)

### ISSUE THREAD

**Issue by wokalski** [graphile/worker#262]
I suggest we do the following [here](https://github.com/graphile/worker/blob/5a09a37e94f49de0d531569f6ca00d5dadd816a5/src/runner.ts#L89-L100).

```diff
    const cron = runCron(options, parsedCronItems, { pgPool, events });
    releasers.push(() => cron.release());

    const workerPool = runTaskList(options, taskList, pgPool);
    releasers.push(() => workerPool.release());

    let running = true;
    return {
      async stop() {
        if (running) {
          running = false;
          events.emit("stop", {});
          await release();
        } else {
          throw new Error("Runner is already stopped");
        }
      },
      addJob,
-      promise: workerPool.promise,
+      promise: Promise.all([workerPool.promise, cron.promise]),
      events,
    };
```

It would be a breaking change. Right now there is a very ugly uncaught exception in case of errors in the cron promise.

**Comment by benjie** [comment]
`cron.promise.then(null, () => {})` should suffice to prevent the crash (which is a new behaviour in Node 16 I believe). What error are you actually getting from cron though?

**Comment by benjie** [comment]
Indeed, looks like I completely overlooked error handling here :grimacing: 

Addressed in https://github.com/graphile/worker/pull/263
