### ISSUE TITLE
Any dashboard UI for this?

### ISSUE THREAD

**Issue by aristofun** [graphile/worker#265]
### Summary

I'm wondering if there's any UI for this worker to monitor current status of the jobs.

**Comment by benjie** [comment]
I believe some people have rolled their own UI, but a UI is currently out of scope for this project.

**Comment by psugihara** [comment]
I saw some screenshots of a dashboard in https://github.com/graphile/worker/pull/82

@stlbucket, is that open source?

I'm looking around for a simple web ui too for monitoring / debugging like sidekiq.

**Comment by stlbucket** [comment]
@psugihara - that was an old dead version

i intend to have an updated version that you could look at soon.  i'll let you know.  maybe it will give you some ideas.

and yeah it is all open source.  but really pretty primitive.

**Comment by psugihara** [comment]
cool! excited to check it out
