### ISSUE TITLE
Add batch schedule jobs

### ISSUE THREAD

**Issue by mahdidarabi** [graphile/worker#284]
### Feature description

Hi and have good time.
please add a function for add many jobs.
for example currently we have a function that gives a job and adds that job:
addJob({identifier, payload, spec}: Job): JobResponse
and now we want to add a function that gives list of jobs and adds jobs:
addJobs(jobs :Job[]): JobResponse[]

### Supporting development

I [tick all that apply]:

- [ ] am interested in building this feature myself
- [ ] am interested in collaborating on building this feature
- [ ] am willing to help testing this feature before it's released
- [ ] am willing to write a test-driven test suite for this feature (before it exists)
- [ ] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by benjie** [comment]
We definitely want to do this; but for now you can achieve it yourself with SQL:

```sql
select graphile_worker.add_job(el->'task_identifier', el->'payload' /* add more here if needed */)
from json_array_elements($1::json) el
```

**Comment by benjie** [comment]
https://github.com/graphile/worker#add_jobs

**Comment by mahdidarabi** [comment]
🙏🏻 Thank you
