### ISSUE TITLE
Clarify retry behavior of cron jobs

### ISSUE THREAD

**Issue by spiffytech** [graphile/worker#285]
### Summary

If a cron job keeps failing and getting retried, what happens the next time the job is scheduled? Does another copy of the job start running, in addition to the one that's already enqueued for retry?

**Comment by benjie** [comment]
Yes. If you’d like to change that behaviour, adding another option to `opts` to add a job_key may make sense - let me know if you’d like to work on that and I’ll do a bit more research first.

**Comment by benjie** [comment]
Cool; give me a few days to find a window but I'll do some research and write some suggestions :+1: 

(Or, alternatively, go ahead and do what you think but keep it small and focussed - and don't spend too much time on it in case we go a different direction!)

**Comment by spiffytech** [comment]
Would it make sense to automatically construct the `job_key` for cron jobs from the task name + job opts + payload?

1. Is there a reason someone would schedule multiple copies of a job with identical parameters?
2. Would someone ever want several not-identical jobs to share a job key?

**Comment by benjie** [comment]
> Would it make sense to automatically construct the job_key for cron jobs from the task name + job opts + payload?

No.

> Is there a reason someone would schedule multiple copies of a job with identical parameters?

Yes; a "hourly summary" report generator should make reports for every hour even if the worker were shut down for 6 hours. A monthly bill generator should generate a bill for every month even if it missed the window - that's why we have backfill :)

Note:

> Each crontab job will have a JSON object payload containing the key _cron with the value being an object with the following entries:
> - ts - ISO8601 timestamp representing when this job was due to execute
> - backfilled - true if the task was "backfilled" (i.e. it wasn't scheduled on time), false otherwise

> Would someone ever want several not-identical jobs to share a job key?

Potentially. If you do an hourly and daily notifications summary you might want them to share the same job key such that if the hourlies were delayed and the daily went out it would replace all the hourlies.

**Comment by spiffytech** [comment]
Alright, it sounds like a manual job key is the right way to go. I'll dig into implementing it.

**Comment by benjie** [comment]
I think add a `jobKey` and `jobKeyMode` entries to [`CronItemOptions`](https://github.com/graphile/worker/blob/9d484820b97f0f4f677dccdf810905547ee2e74c/src/interfaces.ts#L172-L187) via [`?jobKey=string&jobKeyMode=replace` opts](https://github.com/graphile/worker/blob/main/README.md?plain=1#L1347-L1348). You'll need to add support in a few places, especially here: https://github.com/graphile/worker/blob/9d484820b97f0f4f677dccdf810905547ee2e74c/src/cron.ts#L124 and https://github.com/graphile/worker/blob/9d484820b97f0f4f677dccdf810905547ee2e74c/src/cron.ts#L147

My main concern is that the call to `add_job` here:

https://github.com/graphile/worker/blob/9d484820b97f0f4f677dccdf810905547ee2e74c/src/cron.ts#L140

should be using the bulk add API `add_jobs` instead (please don't do that in this PR - I prefer separate PRs for separate features). As such, the `jobKeyMode` behavior is different - namely we don't support `unsafe_dedupe` and `replace`/`preserve_run_at` need to be transformed to the `job_key_preserve_run_at` boolean here:

https://github.com/graphile/worker/blob/9d484820b97f0f4f677dccdf810905547ee2e74c/__tests__/schema.sql#L114

I think the best way to solve this right now is that when you implement it you explicitly state (and validate!) that `jobKeyMode` only accepts `replace` and `preserve_run_at`.

**Comment by spiffytech** [comment]
I've got some implementation work done, now figuring out tests.

**Comment by benjie** [comment]
Implemented in #294  :raised_hands:
