### ISSUE TITLE
Error: Disallowed template name

### ISSUE THREAD

**Issue by paranoico** [graphile/worker#290]
### Summary

I have found that template or task filenames are not allowed to contain special characters, like spanish accent.
For instance, we get an error saying:
**Error: Disallowed template name 'alen_éxito.mjml'**

As you can see , the error is en the **é** vowel.

Why is this behavior?

Does it have some problems with the rest of the code? Can we erase such filename validation?

To me it is strange to only allow english characters, at least it looks like that.

Thanks in advance.

**Comment by benjie** [comment]
I don’t think worker has any rules related to MJML files. Did you mean to file this against starter?

**Comment by paranoico** [comment]
Well, the error regarding the MJML belongs to the starter, you are right, in this line:
[MJML filename check](https://github.com/graphile/starter/blob/40e1e94b507172339f23ee1069ce4db9fa635ac5/%40app/worker/src/tasks/send_email.ts#L74)
```
      if (!template.match(/^[a-zA-Z0-9_.-]+$/)) {
        throw new Error(`Disallowed template name '${template}'`);
      }
```

And in the worker, the error is in this line:
[Task filename chek](https://github.com/graphile/worker/blob/b64b4b1cae3ed8f7b8e467e6ad77e43e409cb978/perfTest/init.js#L8)
```
if (!taskIdentifier.match(/^[a-zA-Z0-9_]+$/)) {
  // Validate so we can do raw SQL
  throw new Error("Disallowed task identifier");
}
```

So i thought could report it here, my apologize if i was wrong.

Thanks @benjie

**Comment by benjie** [comment]
You may edit starter as you wish; likely the check was a lazy one to ensure Win/Lin/Mac compat; it’s generally safest to start with the strictest validations and losen them as needs arise.

**Comment by paranoico** [comment]
Thanks a lot @benjie
