### ISSUE TITLE
`run` with idle timeout

### ISSUE THREAD

**Issue by tonyxiao** [graphile/worker#297]
I intend to use worker in a serverless environment where every minute we trigger run function of the worker to execute pending tasks. So `run` indefinitely isn't an option as there are infra level timeout associated with the serverless function. And `runOnce` exits a bit too quickly such that the latency for executing tasks can become up to 1 minute. It would be ideal if there are some levels of control, for example where `run` times out after 30 seconds. So that max latency for running tasks can be lowered to 30 seconds (or anything user configurable) while also preserving CPU/memory resources while waiting.

**Comment by tonyxiao** [comment]
The other issue with `runOnce` appears to be that it does not take into account crontabs (more specifically, backfilling crontabs)

**Comment by benjie** [comment]
I do not want to add this; however you could emulate it by using the event system to detect activity and a timer to call the release function.

**Comment by tonyxiao** [comment]
Got it, thanks for the implementation suggestion!

**Comment by tonyxiao** [comment]
For those curious, here's the code

```ts
  let idleTimeout: NodeJS.Timeout | undefined = undefined

  runner.events.addListener('job:start', () => {
    if (idleTimeout) {
      console.log('Starting job and clearing idleTimeout')
      clearTimeout(idleTimeout)
      idleTimeout = undefined
    }
  })

  runner.events.addListener('worker:getJob:empty', () => {
    if (!opts.timeout || idleTimeout) {
      return
    }
    console.log(`No job, will wait ${opts.timeout}ms then quit`)
    idleTimeout = setTimeout(async () => {
      console.log('Runner timeout, exiting...')
      await runner.stop()
    }, opts.timeout)
  })
```

**Comment by benjie** [comment]
Thanks for sharing!

**Comment by trompx** [comment]
> For those curious, here's the code
> 
> ```ts
>   let idleTimeout: NodeJS.Timeout | undefined = undefined
> 
>   runner.events.addListener('job:start', () => {
>     if (idleTimeout) {
>       console.log('Starting job and clearing idleTimeout')
>       clearTimeout(idleTimeout)
>       idleTimeout = undefined
>     }
>   })
> 
>   runner.events.addListener('worker:getJob:empty', () => {
>     if (!opts.timeout || idleTimeout) {
>       return
>     }
>     console.log(`No job, will wait ${opts.timeout}ms then quit`)
>     idleTimeout = setTimeout(async () => {
>       console.log('Runner timeout, exiting...')
>       await runner.stop()
>     }, opts.timeout)
>   })
> ```

Thanks for sharing @tonyxiao. Do you use aws lambda? By any chance would you have a small repo where I could get a glimpse of how all of this tie together?
