### ISSUE TITLE
Shouldn't signal logs be something else other than `error`?

### ISSUE THREAD

**Issue by jpcbarros** [graphile/worker#298]
### Summary

When executing graceful shutdowns we're seeing some errors logs coming from graphile-worker when it receives signals to shutdown. Shouldn't those logs be informational rather than of `error` level?

### Additional context

See the code here:
https://github.com/graphile/worker/blob/af85e51e9da62ebb811bc867eb2d5a827c01cd62/src/main.ts#L85

**Comment by benjie** [comment]
If it was a choice between stdout and stderr I’d send them to stderr. I’m happy with them being error 🤷‍♂️
