### ISSUE TITLE
run worker without migration

### ISSUE THREAD

**Issue by tonyxiao** [graphile/worker#299]
There is already the `--schema-only` option, what we are looking for is opposite - in other words `--no-schema` option

Couple issues with the current approach

1) pg user that worker uses may not have the privilege to modify database schema for security reasons. 
2) It can be easier to maintain for all migrations to be centrally run / managed
3) Embedded `sql` files do not work out of the box in certain scenarios where we want worker to run (Example below)

I just tried to run worker inside a next.js function called `worker` and got the following error.

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/696842/198006575-96b27c29-598a-45f1-89f6-c475e912bd5d.png">

**Comment by tonyxiao** [comment]
@benjie do you have workaround suggestions in the meantime?

**Comment by benjie** [comment]
The workaround is to have all the migrations already executed when you run the library - we'll check the latest migration, find it has completed, and won't try and run it.

**Comment by tonyxiao** [comment]
The problem is that it still looks for the `.sql` file and that's currently breaking in the case where the javascript is being bundled (e.g. by nextjs / vercel) and therefore the `../sql` directory is not found. Would you be open to a PR where we check the existence of the `../sql` directory and handle gracefully / skip migration if dir not found?

**Comment by benjie** [comment]
Right; that's a different problem entirely. We can add a build step to inline the SQL into a file so that no FS access is needed. In fact, there's already an open issue for that: https://github.com/graphile/worker/issues/143

**Comment by benjie** [comment]
Counting this as fixed by #345
