### ISSUE TITLE
0.14.0 release

### ISSUE THREAD

**Issue by jowparks** [graphile/worker#302]
### Summary
I see release notes for 0.14.0 (I am trying to use the batch jobs), but the latest version on npm is `0.13.0`

**Comment by benjie** [comment]
v0.14.0-alpha.0 is available to use on npm; I'm waiting for more feedback from users before I tag it as `@latest` but it should be fine. No-one has reported any issues (or any successes) as of yet.

**Comment by codetheweb** [comment]
hey @benjie, is there any update on the timeline for releasing 0.14.0? There's lots of cool stuff in 0.14 that we're interested in using, just a little wary of upgrading to something tagged alpha.

**Comment by benjie** [comment]
Still waiting for feedback. Kinda a catch 22 right now: everyone wants it but no-one’s testing it. 🤷‍♂️

Let me know how you get on with it.

**Comment by benjie** [comment]
The alpha is just to allow us to redo the migration and/or API based on feedback, it should run fine.

**Comment by benjie** [comment]
I've now released it as `graphile-worker@0.14.0-rc.0` to remove the word `alpha` for you.
