### ISSUE TITLE
Multiple duplicated jobs added despite having job key (replace or preserve_run_at mode)

### ISSUE THREAD

**Issue by tonyxiao** [graphile/worker#303]
If there is an existing job already in progress with the given key, trying to add a new job with job_key_mode of `replace` shall cause a new job to be added with the key missing. As a result of this, multiple duplicate jobs can thus be added. 

Confirmed this does not occur in `unsafe_dedupe` mode. 

Tested as of v0.13.0

**Comment by benjie** [comment]
Yes, this behaviour is by design. Unsafe_dedupe exists specifically to not do this, but doing so is unsafe as explained in the documentation - namely that the job _is already running_ so any new information in the job that you attempt to queue will be lost.

**Comment by tonyxiao** [comment]
perhaps it could compare the payload and config of the job? 

The most unexpected part about this is that it is allowing the user to add not just one due to the fact that one is running, but MANY duplicate jobs all of whom are missing job_key that the user specified. When you specify a job key, you'd expect that job key to be there on the final job that gets queued. 

While there are some docs on `unsafe_dedupe`, there's no mention of this behavior when using `replace`.

**Comment by benjie** [comment]
That shouldn’t be the case; the new jobs should get a job key, the key is only removed when a new job comes in and the old one is already running. If you set a run_at 5 minutes in the future can you reproduce this issue?

**Comment by tonyxiao** [comment]
Interesting. So the key is removed from old job, rather than removed from the new job. So if I end up with a whole bunch of jobs without keys, it's likely that they are the old jobs that keep having their key removed, not new job being added without key right?

**Comment by benjie** [comment]
Correct

**Comment by benjie** [comment]
We remove the key _and_ set the attempts to max attempts so that even if it fails it will never run again.
