### ISSUE TITLE
Jobs are getting replaced 

### ISSUE THREAD

**Issue by sandrodesouza** [graphile/worker#312]
hey guys, I think I just found a bug on graphile worker but I want to check here before open an issue. 
When adding 2 jobs with distinct identifiers but with same jobKey, one replace the other. 
F.i.: 
await addJob("task_1", { foo: "bar" }, { jobKey:1 });
await addJob("task_2", { foo: "bar" }, { jobKey:1 });

This will end with just one job on our job table.

Just wondering if is the correct behavior or a bug

**Comment by benjie** [comment]
That's by design. It allows you to change the task identifier for a job. For example you might schedule an email, but when something else happens later you might upgrade that task to an SMS instead.

Please see the second IMPORTANT entry here: https://github.com/graphile/worker#job_key-caveats
