### ISSUE TITLE
Batch jobs with concurrency per job type : optimize waiting time

### ISSUE THREAD

**Issue by trompx** [graphile/worker#320]
Hello, I have the following usecase. I need to process jobs while respecting a concurrency per job type.
Example: 10 jobs:
- type 1 (jobs 1-6) : concurrency 3
- type 2 (jobs 7-10) : concurrency 2

Those jobs hit an API which have response time ranging from 2-10s.
I need to run the worker in a serverless environment (lambda). As lambda is pay per execution time, I want to optimize the waiting time. So I plan to batch those jobs.

I am not sure I fully understand the graphile-worker batch jobs feature and if it can help in my case. Is it possible to create a batch job by passing the 10 jobs in the array with their concurrency setting, then, in a loop, processing concurrently 3 jobs of type 1 and 2 jobs of type 2. As soon as one job completes, process the next one respecting the job type concurrency. If one API request fails, update the payload so that the job will stay in the queue and be tried again respecting the max_attempts?
Or the batch job will respect the worker global concurrency thus if I want to apply per job type concurrency, I'll have to do something custom, like what you suggested in https://github.com/graphile/worker/issues/118 where I would control the concurrency in redis and set the graphile worker concurrency to 1? Problem is I also plan to use redis serverless which is expensive and doing rate limit check at each loop would be a problem, so was thinking of controlling the concurrency at schedule time and manage it inside the batch job with bluebird or equivalent.

**Comment by benjie** [comment]
Graphile Worker has the following for concurrency patterns:

- Concurrency: unlimited - use unnamed queues and an unlimited number of worker processes
- Concurrency: 1 - use a single named queue
- Concurrency: N - either:
  - run N workers with concurrency 1
  - run 1 worker with concurrency N
  - use "round robin" job enqueuing by queueing the jobs to N named queues (`queue_1`, `queue_2`, etc)
  - do something custom with batched jobs (in a single named queue)

If you select the latter of these (using batched jobs) then the batch size is unbounded but your task itself could split the work however it sees fit - it's just JavaScript.

Graphile Worker is not designed for N-level concurrency problems, and I do not care to add it as a first class feature, so if you really need it, it's down to you to manage.
