### ISSUE TITLE
Unable to give database users ability to query some tables in graphile_worker schema

### ISSUE THREAD

**Issue by WTPascoe** [graphile/worker#323]
### Summary

I'm unable to give other database users the ability to query certain `graphile_worker` tables, but others work fine.

When the `developers` user does `SELECT * FROM graphile_worker.known_crontabs` 0 rows are returned, but no permission or access error is shown. When the primary user does this, 12 rows are returned.

The `developers` user **is** able to select from `graphile_worker.migrations` and gets the same rows back as the primary user.

### Additional context

We are using Google Cloud  PostgreSQL 14. We have added a number of additional users and granted them permissions on the database and schemas with our primary user as follows:

```
GRANT CONNECT ON DATABASE "my-dbname" to "developers";
GRANT USAGE ON SCHEMA public TO "developers";
GRANT USAGE ON SCHEMA graphile_worker TO "developers";
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA graphile_worker to "developers";
GRANT ALL ON ALL SEQUENCES IN SCHEMA graphile_worker to "developers";
GRANT ALL ON ALL TABLES IN SCHEMA graphile_worker TO "developers";
GRANT SELECT ON ALL TABLES IN SCHEMA public TO "developers";
```

Each of these commands succeeds with a `GRANT` response.

I then login with the developers user, and get these results:

_Success_
```
my-dbname=> select * from graphile_worker.migrations;
 id |              ts
----+-------------------------------
  1 | 2023-04-20 19:58:29.230567+00
  2 | 2023-04-20 19:58:29.355976+00
  3 | 2023-04-20 19:58:29.442215+00
```

_Failure_
```
my-dbname=> select * from graphile_worker.known_crontabs;
 identifier | known_since | last_execution
------------+-------------+----------------
(0 rows)
```

When I run the same with my primary database user, I get multiple rows returned
```
my-dbname=> select * from graphile_worker.known_crontabs;
                        identifier                        |        known_since         |     last_execution
----------------------------------------------------------+----------------------------+------------------------
REDACTED
(12 rows)
```

**Comment by benjie** [comment]
Those are not public interfaces so you shouldn’t use them. Use the functions to interact with Graphile Worker, and call them using the same user that Graphile Worker was installed under (or a superuser).

That said, the reason for your issue is because the tables have row level security enabled. Disable it or add policies at your own risk.
