### ISSUE TITLE
0.14.0 release

### ISSUE THREAD

**Issue by codetheweb** [graphile/worker#326]
(Continuing the conversation from https://github.com/graphile/worker/issues/302, figured it'd be better to open a new issue than continue to discuss in a closed issue.)

We've upgraded two services to [0.14.0-rc.0](https://github.com/graphile/worker/commit/5b9f85854967f33a82faef77221f478b384ef8a2) and so far everything's been working great.

Our only (slight) pain point is having to join an extra table now that `task_identifier -> tasks.identifier`. I realize running queries directly against the `graphile_worker` schema isn't a supported interface, but we need to be able to do things like count queued jobs based on contents of the payload. We only execute `SELECT`s and never mutate anything within `graphile_worker`. (Not a blocking issue by any means, just was wondering if there's a better way to do this.)

Will continue to update this issue for the next week or so if anything comes up.

**Comment by benjie** [comment]
The task identifiers table is permanent, so you could just query that each time you see a new task identifier id you don’t recognise and cache it in memory.
