### ISSUE TITLE
How retrieve pending jobs

### ISSUE THREAD

**Issue by lkostrowski** [graphile/worker#330]
### Summary

Hi, I started exploring this lib and I really enjoy its simplicity. However I struggle to achieve one goal

After my job is finished I want to inform frontend about it. 
My initial approach is setInterval that asks my endpoint. The endpoint should call worker to get pending jobs queue, filter them (e.g. get specific ID) and return to the frontend its status

How do I do that?

I know that I can
1. Check raw database - I don't want to dig into internal schema
2. Work around with event `job:complete` but it requires me to open a websocket or store results in the memory. I risk losing the state
3. Store result in my database

If result is important (like an event log), I'd pick option 3, but for instant feedback I'd prefer to have some API that calls DB and returns me ongoing jobs.

**Comment by benjie** [comment]
Providing this functionality is explicitly a non-goal of Graphile Worker - you must provide this functionality for yourself.

The way *I* would do it is:

1. When creating the job that needs to be monitored, add an entry to a "actions" (or similar) table that I control, and log that action id into the job
2. Add a trigger to the "actions" table that issues `NOTIFY` commands when a row is updated
3. When the job starts, update that action to say "in progress"
4. (Optionally) during job execution, update the progress of that action with an estimated percentage
5. Wrap the task in try/catch and on error update the action to say 'errored' - then rethrow the error
6. On success, update the action to say "completed"

Have the client subscribe to these changes - in PostGraphile you could do this with a GraphQL subscription, for example, but I don't know what backend you are using.

Generally polling should be avoided, but it could be used as a backup.
