### ISSUE TITLE
Sub-queues for fairness within a queue

### ISSUE THREAD

**Issue by WesleyYue** [graphile/worker#331]
### Summary
Is there any feature or recommended pattern we can use to achieve the same thing as [Groups feature in bullmq](https://docs.bullmq.io/bullmq-pro/groups)? The problem I'm looking to solve is to allow users to queue jobs, but work on them fairly so that one user queuing 100k jobs doesn't consume all the worker capacity for other users.

**Comment by benjie** [comment]
There’s nothing natively implemented to do exactly this, but here’s two ways I can think of to do something like this:

1. use forbidden flags to temporarily block jobs from users who have ran recently: https://github.com/graphile/worker#forbidden-flags
2. implement the roundrobin in your task: the task is simply a “run next” and you track everything to run in a different table with arbitrary grouping/etc - it then plucks the next thing from that table using whatever logic you like (and marks it as consumed)
