### ISSUE TITLE
Downsides of indexing the `task_identifier` column.

### ISSUE THREAD

**Issue by RisbergAdam** [graphile/worker#333]
### Summary

Downsides of indexing the `task_identifier` column.

### Additional context

Hi! 👋 We've implemented a feature in our graphile-worker setup that allows us to pause the processing of a subset of task types. We did this by not registering task handlers for the specific tasks that we want to pause but we are running into performance issue causing our database CPU to hit 100% when our job queue contains a large amount of jobs (>1M) that are all paused.

Some debugging indicates that the `get_job` procedure used by workers to poll available jobs has to scan the full jobs table before returning since all jobs are filtered by the `task_identifier` clause in the procedure.

Indexing the `task_identifier` seems to solve it locally but I'm wondering if there is any expected downsides by doing this? I would assume job enqueueing performance would take a hit, but is there anything else?

**Comment by benjie** [comment]
Job enqueueing would indeed take a hit, and query planning might take a fraction of a millisecond longer, but if this boosts your runtime performance it may well be worth it.

Before you go making this kind of change though, I'd encourage you to ensure you're running the 0.14.0 release which has some very significant performance improvements for large jobs tables such as yours:

https://github.com/graphile/worker/blob/main/RELEASE_NOTES.md#v0140

`0.14.0-rc.0` is available on npm; let me know how you get on.

(Note that the indexes in 0.14.0-rc.0 include the `task_id` column, so shouldn't require a table scan - only an index scan in the worst case.)

```sql
CREATE INDEX jobs_main_index ON graphile_worker.jobs
  USING btree (priority, run_at)
  INCLUDE (id, task_id, job_queue_id)
  WHERE (is_available = true);
CREATE INDEX jobs_no_queue_index ON graphile_worker.jobs
  USING btree (priority, run_at)
  INCLUDE (id, task_id)
  WHERE ((is_available = true) AND (job_queue_id IS NULL));
```
