### ISSUE TITLE
Run once alias option not working

### ISSUE THREAD

**Issue by madflow** [graphile/worker#34]
```js
$ /tmp/aaa/node_modules/.bin/graphile-worker --help
Optionen:
  --help            Hilfe anzeigen                                     [boolean]
  --version         Version anzeigen                                   [boolean]
  --connection, -c  Database connection string, defaults to the 'DATABASE_URL'
                    envvar                                              [string]
  --once, -1        Run until there are no runnable jobs left, then exit
                                                     [boolean] [Standard: false]
  --watch, -w       [EXPERIMENTAL] Watch task files for changes, automatically
                    reloading the task code without restarting worker
                                                     [boolean] [Standard: false]
  --jobs, -j        number of jobs to run concurrently             [Standard: 1]
  --poll-interval   how long to wait between polling for jobs in milliseconds
                    (for jobs scheduled in the future/retries)
                                                         [Zahl] [Standard: 2000]
```

* ` yarn run graphile-worker -c invalid` => Alias is working
* ` yarn run graphile-worker -1` => Alias is **not** working
* ` yarn run graphile-worker --1` => Alias is  working

**Comment by benjie** [comment]
Interesting; this might be an issue in `yargs`: 

https://github.com/graphile/worker/blob/e888cfc168f657c8299d981123b86aa7ed8874cf/src/cli.ts#L17

Do dig in if you're interested :)

**Comment by benjie** [comment]
(Solution might be to just drop that alias.)

**Comment by madflow** [comment]
I am digging in on #13 at the moment ;). There is the idea of a `-0` alias - that is where I encountered this. Very probably a yargs bug. My favorite would be to drop the aliases :p - they are not very intuitive for my taste.

**Comment by madflow** [comment]
I created an upstream issue anyway: https://github.com/yargs/yargs/issues/1454

**Comment by benjie** [comment]
I'm absolutely on-board with dropping aliases; except that's a breaking change.

**Comment by madflow** [comment]
Yeah, this came to my mind, too. Maybe it can be fixed with some config yargs quirks or it is just a bug.
