### ISSUE TITLE
Question: Does this need to run in a separate process?

### ISSUE THREAD

**Issue by roemhildtg** [graphile/worker#35]
This is probably a dumb question but I'm wondering if I can use this inside an existing web app (express). 

Lets say I'm adding tasks that'll take upwards of 1-2 minutes to complete, will the tasks run in a separate thread/process? Or will there be a negative impact on my server?

**Comment by roemhildtg** [comment]
I guess to further clarify - I have this example working:

```javascript

// express app index.js
// ....
server.on('listening', () => {
    logger.info(port);
    logger.info('Feathers application started on http://%s:%d', app.get('host'), port);
});

// further down in the file...
const exe = `${__dirname.replace('\\', '/')}/node_modules/graphile-worker/dist/cli.js`;
const taskQueue = spawn('node', [
    exe,
    '-c',
    '"postgres://postgres:pgadmin@172.17.49.84:5432/wsb_datafi_services"',
]);

taskQueue.stdout.on('data', (data) => console.log(`taskQueue: ${data}`));
taskQueue.stderr.on('data', (data) => console.log(`taskQueue (error): ${data}`));
taskQueue.on('error', (data) => console.log(`taskQueue (error): ${data}`));
taskQueue.on('close', (data) => console.log(`taskQueue (close): ${data}`));
```

**Comment by benjie** [comment]
You’re running the worker in a separate task there 👍. The worker in library mode does NOT run in a separate thread, it uses standard node concurrency patterns. If your tasks are IO-heavy and CPU-light then it should be okay to run in the same process but I recommend you move it to a separate process before you get harder tasks/heavier traffic.

What you have seems fine 👍

**Comment by roemhildtg** [comment]
Cool! Thanks for the feedback, it is much appreciated.
