### ISSUE TITLE
Make job cancellation optional during shutdown

### ISSUE THREAD

**Issue by keslerm** [graphile/worker#352]
### Feature description
Add a flag to not cancel jobs during the graceful shutdown procedure.

### Motivating example
Currently when the handlers receive a SIGTERM signal it triggers a cancellation of running jobs which stops them from running. This is probably find most of the time but sometimes you might want to wait the currently running jobs complete and then shut down.

### Breaking changes

I don't think adding this flag would break any changes. I guess in general I could write my own signal handler to do this but i think:

1. It's probably a fairly common use case
2. The documentation itself implies this is already the expected handling:

> If the worker is terminated (SIGTERM, SIGINT, etc), it [triggers a graceful shutdown](https://github.com/graphile/worker/blob/3540df5ab4eb73f846d54959fdfad07897b616f0/src/main.ts#L39-L66) - i.e. it stops accepting new jobs, waits for the existing jobs to complete, and then exits. If you need to restart your worker, you should do so using this graceful process.

### Supporting development

- [ ] am interested in building this feature myself
- [X] am interested in collaborating on building this feature
- [X] am willing to help testing this feature before it's released
- [ ] am willing to write a test-driven test suite for this feature (before it exists)
- [ ] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by benjie** [comment]
Yes this definitely needs some attention. What we really need is:

- First interrupt: tell workers to stop accepting new jobs, and exit once all jobs are complete
- (Ignore all signals for 5 seconds - output a message saying you're ignoring it, and how long for)
- Second interrupt (some time after this 5 second "ignore" period): have each worker unlock any jobs that are still active, and then terminate the process (by sending itself the signal again) once all workers have completed this
- Third interrupt (any time after the second): exit (automatically, by having no signal handers).

What we have right now (from scanning the code quickly) is that the first interrupt effectively does the second interrupt's behavior... and that's not right.

**Comment by nnaku** [comment]
First time I saw this issue, I was scared about idea that some jobs could be canceled for example during the deployment (instance receives SIGTERM when next one is up and running). But that doesn't seem to happen for me, does the worker work as expected or do I need a more detailed setup to get jobs canceled during shut down? Our current setup has signal handling and and it will call `runner.stop` during shutdown. 

I'm just trying to understand that if there is possibility to lose/cancel jobs when it might happen? 🙂

**Comment by benjie** [comment]
This is out in `graphile-worker@0.15.1`
