### ISSUE TITLE
Question: What happens to the task result?

### ISSUE THREAD

**Issue by roemhildtg** [graphile/worker#36]
I noticed that while the task is running, it is available in postgres, but I'm wondering what if the function returns a result, like a json or string object? Can that result be stored as a JOB_RESULT or something? Maybe I need to investigate under the hood a bit.

**Comment by benjie** [comment]
We don’t have that feature; in fact when the job completes we delete it. The job itself can write data somewhere but the return result it currently ignored.

**Comment by roemhildtg** [comment]
Okay good to know. Thanks again!
