### ISSUE TITLE
New 0.1.0-alpha release?

### ISSUE THREAD

**Issue by keithlayne** [graphile/worker#37]
There are some new features since the last alpha release that I  am using.  I can use master but would you mind cutting a new alpha?  Thanks!

**Comment by keithlayne** [comment]
So I may have just spoken too soon, just reviewed the commits, and it looks like `DATABASE_URL` is the only real change.  Easy to work around, sorry for the noise.

**Comment by benjie** [comment]
(Here's the changes for anyone else interested:

https://github.com/graphile/worker/compare/v0.1.0-alpha.0..master

Very little of this relates to the code.)

**Comment by benjie** [comment]
:man_shrugging: I've released it as v0.1.0.
