### ISSUE TITLE
Request a feature: Pause running worker thread

### ISSUE THREAD

**Issue by nnaku** [graphile/worker#377]
### ✨ Request a feature
Administrative function (sql interface) for suspending or pausing the running worker thread(s).
i.e database flag for worker which determines should it process next job or not. 

### 💭 Motivation
Update v0.14.0 introduced breaking changes and I'm totally fine with that! Actively developed software goes through iterations and some times it's required to fine tune the core parts to and support the future plans!

How ever this update put me in an awkward situation. In which I may have to temporarily shut down the application and cause inconvenience to the end users because we are running our software in multiple instance and all those instances are process jobs and responsible for other functionality of the application (e.g. serving web and api's). Our deployment is shutting down old and starting up new build instances one by one, so there at least one healthy instance running all the time. Now worker migrations required that there is no locked jobs or migration will fail. And because there is multiple instances running workers it is almost 100% sure that there are running/locked jobs always! 

But if I could keep software running and pause only the job processing. I can do the things that required 0 locked jobs while app is running. 

### Breaking changes

I can't see any 🤷 

### Supporting development

- [x] am interested in building this feature myself
- [x] am interested in collaborating on building this feature
- [x] am willing to help testing this feature before it's released
- [x] am willing to write a test-driven test suite for this feature (before it exists)
- [ ] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

# 🙏 Thank you!
I'd like to give a big thanks for nice piece of code! worker is awesome! It seems to me that graphile worker will become our goto background processing tool.

**Comment by nicktrn** [comment]
Hey @nnaku, we're stuck in a similar situation.

A couple of questions re your proposal:

- What should "pausing" do in practice? Say a job is being processed and locked by worker X. What happens to that job when X pauses?
- Would you want to "resume" that job? What would that look like?

We took a slightly different approach and backported some of the recently released fixes:

1. Fixed graceful shutdown as per #353
2. Added graceful shutdown on migration detection as per #361 

We already had a suitable wrapper around `graphile-worker` so this was fairly straightforward.

Happy to provide TypeScript examples if that's helpful. That being said, we have yet to migrate :crossed_fingers:

**Comment by benjie** [comment]
(0.16 is going to be a big change too, so it might be wise to jump straight from 0.13 to 0.16 rather than doing the 0.14 bump in between.)

**Comment by benjie** [comment]
0.16 is now released; announcement here: https://worker.graphile.org/news/2023-12-01-016-release

Worker Pro has a feature that aids with migrations without "scaling to zero": https://worker.graphile.org/docs/pro/migration

I think that feature implements enough to satisfy this need (and if not then the plugin interface hopefully gives you the ability to do it yourself, and that interface has been backported to 0.13 and 0.15 to give you an easier time).
