### ISSUE TITLE
nudge called after worker terminated

### ISSUE THREAD

**Issue by FlowerWrong** [graphile/worker#381]
### Summary

Sometimes when I start the worker, it failed, but after a while, it is ok.

### Additional context

```javascript
node:assert:399
    throw err;
    ^

AssertionError [ERR_ASSERTION]: nudge called after worker terminated
    at Object.nudge (/app/node_modules/graphile-worker/dist/worker.js:51:9)
    at /app/node_modules/graphile-worker/dist/main.js:366:49
    at Array.some (<anonymous>)
    at Client.handleNotification (/app/node_modules/graphile-worker/dist/main.js:366:25)
    at Client.emit (node:events:513:28)
    at Client._handleNotification (/app/node_modules/graphile-worker/node_modules/pg/lib/client.js:394:10)
    at Connection.emit (node:events:513:28)
    at /app/node_modules/graphile-worker/node_modules/pg/lib/connection.js:116:12
    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:40:17)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

Node.js v18.16.0
```

**Comment by benjie** [comment]
What version of Worker are you running?

**Comment by FlowerWrong** [comment]
> What version of Worker are you running?

[v0.15.1](https://github.com/graphile/worker/releases/tag/v0.15.1)

It only happened once before, but now it happens often.

**Comment by FlowerWrong** [comment]
Only one worker on a server can run normally, and other workers report this error `nudge called after worker terminated`.

**Comment by benjie** [comment]
That seems suboptimal; you should investigate why your worker is terminating in the first place - are you having connection issues with the database? Exhausting a connection limit? Unstable network connection? Are you sending it terminate or interrupt or similar signals?

**Comment by FlowerWrong** [comment]
> That seems suboptimal; you should investigate why your worker is terminating in the first place - are you having connection issues with the database? Exhausting a connection limit? Unstable network connection? Are you sending it terminate or interrupt or similar signals?

Hi! @benjie . Can you explain to me under what circumstances this error occurs? I met it again.

**Comment by benjie** [comment]
When a worker is terminated, it gains `active=false`.

When nudge is called on a worker and `active=false`, you get the error `nudge called after worker terminated`.

`nudge()` is called when a pool receives a notification saying there's a new job available.

Hitting this reveals a bug (which is fixed in 0.16 I believe), but the actual termination of the worker is really the issue for you if you're getting it a lot. If the worker is already terminating and you hit this error it's no big deal since you're already exiting anyway.

**Comment by FlowerWrong** [comment]
> When a worker is terminated, it gains `active=false`.
> 
> When nudge is called on a worker and `active=false`, you get the error `nudge called after worker terminated`.
> 
> `nudge()` is called when a pool receives a notification saying there's a new job available.
> 
> Hitting this reveals a bug (which is fixed in 0.16 I believe), but the actual termination of the worker is really the issue for you if you're getting it a lot. If the worker is already terminating and you hit this error it's no big deal since you're already exiting anyway.

Hi! @benjie , does this [commit](https://github.com/graphile/worker/commit/911080fc6f5d62efe0d879ee17e5c92f5bc11501) is for this issue?

**Comment by benjie** [comment]
No

**Comment by FlowerWrong** [comment]
> No

One of my workers has a total of 10 thread pools. After debugging, one of the threads failed to obtain runnable tasks 10 times, resulting in `contiguousErrors >= maxContiguousErrors` and triggering release worker.

`Error: Failed 10 times in a row to acquire job; latest error: No runnable tasks!`

```
logger.debug(`Failed to acquire job: ${err.message} (${contiguousErrors}/${maxContiguousErrors})`);
                if (contiguousErrors >= maxContiguousErrors) {
                    promise.reject(new Error(`Failed ${contiguousErrors} times in a row to acquire job; latest error: ${err.message}`));
                    release();
                    return;
                }
```

**Comment by benjie** [comment]
Ah! That makes a lot of sense! That has been removed in v0.16, it will just keep trying indefinitely now, so this should be fixed for you once the release goes out and you upgrade 👍

**Comment by benjie** [comment]
(Note this removal has also been backported to 0.13 and 0.15 branches via the `-bridge` releases. Read the release notes carefully, and use `yarn add graphile-worker@bridge15` (or equivalent) to install
