### ISSUE TITLE
worker events misbehaving

### ISSUE THREAD

**Issue by timelf123** [graphile/worker#385]
### Summary

Events like `worker:create, worker:stop, stop` etc would be helpful to establish a heartbeat but some events are not firing.

### Steps to reproduce
https://github.com/timelf123/worker/tree/events-repro or 
add these listeners directly below [the runner](https://github.com/graphile/worker/blob/main/examples/readme/events.js#L21) `const runner = await run({...`  and run `worker/examples/readme> npx tsc && node .\events.js` 
```js
  runner.events.on("worker:create", async () => {
    console.log(`[runner] worker:create`);
  });

  runner.events.on("worker:stop", async () => {
    console.log(`[runner] worker:stop`);
  });

  runner.events.on("stop", async () => {
    console.log(`[runner] stop`);
  });
  ```
  
### Expected results

Listeners are registered before events are sent and all documented events work as expected

### Actual results
Tried on node 18/20

| event         | trunk | 0.15.0 |
|---------------|-------|--------|
| worker:create | ❌     | ❌      |
| worker:stop   | ❌     | ✅      |
| stop          | ✅     | ❌      |
| job:success | ❌     |  ✅     |

### Additional context

logs from HEAD (13dc8ce2b4897f4f0c05f7d95ccd789ac87af514)
```
> npx tsc && node events.js
[core] INFO: Worker connected and looking for jobs... (task names: 'hello')
[job(worker-be7be41f1e04bd937b: hello{4})] INFO: Hello, Bobby Tables
[worker(worker-be7be41f1e04bd937b)] INFO: Completed task 4 (hello, 0.49ms) with success
[core] ERROR: Received 'SIGINT'; attempting global graceful shutdown... (all termination signals will be ignored for the next 5 seconds)
Not unregistering signal handlers as we're shutting down
[runner] stop
[core] ERROR: Global graceful shutdown complete; killing self via SIGINT
```

logs from 0.15.0 (08ba506897917ffb9f85071ffa2357f2e81a6378)
```
> npx tsc && node events.js
[core] INFO: Worker connected and looking for jobs... (task names: 'hello')
[job(worker-6507b0ece326b1ba4e: hello{1})] INFO: Hello, Bobby Tables
Hooray! Worker worker-6507b0ece326b1ba4e completed job 1
[worker(worker-6507b0ece326b1ba4e)] INFO: Completed task 1 (hello) with success (0.69ms)
[core] ERROR: Received 'SIGINT'; attempting graceful shutdown...
[runner] worker:stop
[runner] worker:stop
[runner] worker:stop
[runner] worker:stop
[runner] worker:stop
[core] ERROR: Graceful shutdown attempted; killing self via SIGINT
```

![image](https://github.com/graphile/worker/assets/2816999/c7383aa8-a1e1-4031-acc8-16bb24f0c8bb)
Example repro with logging 
https://github.com/timelf123/worker/tree/events-repro
This showed that there were no listeners registered for the worker:create event

**Comment by benjie** [comment]
If you need to track events before the runner is running, you must pass your own event emitter:

```
const events = new EventEmitter() as WorkerEvents;
events.on(...);
events.on(...);
events.on(...);
const runner = await run({ events, ... })
```

**Comment by timelf123** [comment]
I feel silly. Thank you

**Comment by benjie** [comment]
If you feel this could be improved in the docs, please submit a PR! :heart:

**Comment by ThHareau** [comment]
I was having quite the same problem as you @timelf123 , I took the liberty of creating a PR reusing the examples of this PR. Feel free to have a look :slightly_smiling_face: 

https://github.com/graphile/worker/pull/446
