### ISSUE TITLE
Retry when updating job statuses for certain error codes

### ISSUE THREAD

**Issue by jakebiesinger-storyhealth** [graphile/worker#387]
(Filling from discussion at https://discord.com/channels/489127045289476126/1170123247497523212)

### Feature description

The leasing, releasing, and completion SQL queries that update the `jobs` / `_private_jobs` tables have no mechanism for retrying, even for error codes that indicate that a retry may succeed. It would be awesome to inspect the error code on these operations and retry if appropriate.

From the [error code appendix](https://www.postgresql.org/docs/current/errcodes-appendix.html), the two following codes should be able to be retried without issue:

```
40001  serialization_failure
40P01  deadlock_detected
```

[This docs page](https://www.postgresql.org/docs/current/mvcc-serialization-failure-handling.html) talks about the reasoning behind this change. The page mentions that this may only apply to `REPEATABLE READ` and `SERIALIZABLE` isolation levels, but in my testing (where we have a DB with `default_isolation_level=SERIALIZABLE` but all graphile worker pool connections having `SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL READ COMMITTED`, I'm still seeing these errors, even though nothing but the workers are reading these tables.

### Motivating example

Failures when marking a job as completed: The worker actually completed the task, but the job row isn't deleted and appears to still be leased to the worker -- we won't retry for 4 hours (and shouldn't be retrying anyway)

### Breaking changes

None

### Supporting development

I [tick all that apply]:

- [x] am interested in building this feature myself
- [x] am interested in collaborating on building this feature
- [x] am willing to help testing this feature before it's released
- [x] am willing to write a test-driven test suite for this feature (before it exists)
- [ ] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by benjie** [comment]
Released in v0.16.2
