### ISSUE TITLE
Add pre/post schema update migrations

### ISSUE THREAD

**Issue by ssendev** [graphile/worker#388]
### Feature description

add `graphile-worker --pre pre.sql --post post.sql` switches which add two extra migrations that are run in the update transaction.

### Motivating example

The recent schema updates caused a lot of pain since i used functions that dependet on `add_job()` which caused an `error: cannot drop table graphile_worker.jobs_legacy because other objects depend on it`

Adding your own migrations like these it would greatly simplify updates.
```sql
-- pre.sql
drop function if exists app_private.add_job(text,json,text,timestamp with time zone,integer,text,integer,text[],text);
```

```sql
-- post.sql
create or replace function app_private.add_job(identifier text, payload json DEFAULT NULL::json, queue_name text DEFAULT NULL::text, run_at timestamp with time zone DEFAULT NULL::timestamp with time zone, max_attempts integer DEFAULT NULL::integer, job_key text DEFAULT NULL::text, priority integer DEFAULT NULL::integer, flags text[] DEFAULT NULL::text[], job_key_mode text DEFAULT 'replace'::text) RETURNS graphile_worker.jobs as $$
  select graphile_worker.add_job(identifier, payload, queue_name, run_at, max_attempts, job_key, priority , flags, job_key_mode);
$$ language sql security definer;

```

### Supporting development

I [tick all that apply]:

- [ ] am interested in building this feature myself
- [ ] am interested in collaborating on building this feature
- [x] am willing to help testing this feature before it's released
- [ ] am willing to write a test-driven test suite for this feature (before it exists)
- [ ] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by benjie** [comment]
We now have the `premigrate` and `postmigrate` hooks that you can use for this: https://github.com/graphile/worker/blob/main/src/lib.ts#L275-L281

**Comment by ssendev** [comment]
Ah. nice. I guess i didn't search thoroughly enough.

**Comment by benjie** [comment]
I only added it very recently and it hasn't shipped yet
