### ISSUE TITLE
Make idle delay (polling interval) configurable

### ISSUE THREAD

**Issue by madflow** [graphile/worker#4]
The time between polling for new jobs is pinned to 2000 ms at the moment.

The doc for the `IDLE_DELAY` constant reads:

```
 * IDLE_DELAY: This is how long to wait between polling for jobs.

 * Note: this does NOT need to be short, because we use LISTEN/NOTIFY to be
 * notified when new jobs are added - this is just used in the case where
 * LISTEN/NOTIFY fails for whatever reason.
```
* Question: Is polling also necessary for other use cases? Picking up failed jobs, Running delayed jobs, etc? Or is this really just a safety net.

* Feature Request: Make this constant configurable. I actually would not need such a short polling for my use case and it spams the log files  :). Maybe renaming it to Polling Interval  (POLLING_INTERVAL) would it also make it more clear for what it is doing.

I would be happy to provide a PR, but I am hesitant to just start hacking away on this - since I'd guess there would be some refactoring and moving code around involved.

**Comment by benjie** [comment]
Re question: yes, it’s used for failed/future scheduled jobs too.

PR welcome, rename welcome; `--idle-delay` Should be the CLI flag. Thanks for contributing!

**Comment by benjie** [comment]
Fixed in #5

**Comment by benjie** [comment]
Wait we never renamed it to poll interval... I'll do that now.

**Comment by benjie** [comment]
My comments above were confusing - sorry!

**Comment by benjie** [comment]
Alpha 6 now released 👍

**Comment by madflow** [comment]
:+1: Excellent, thanks!
