### ISSUE TITLE
jobs__decrease_job_queue_count references column that does not exist

### ISSUE THREAD

**Issue by nmummau** [graphile/worker#407]
I pulled the npm repo version 0.15.1 and deployed it to my database via Library mode.
I am using DataGrip to look at the definition of each function within the graphile_worker schema. I noticed that the the trigger `jobs__decrease_job_queue_count` is setting a `"graphile_worker".job_queues` column that does not exist:
![image](https://github.com/graphile/worker/assets/10524529/75d91297-98c2-42c1-979c-4189b0cdc257)

![image](https://github.com/graphile/worker/assets/10524529/89bebc35-fbee-4d46-a93c-dbda4827e667)

**Comment by benjie** [comment]
Yeah I spotted this and cleaned it up in migration 15 which you linked above and is part of 0.16.0-rc.1. The reference is harmless since the trigger isn’t used.
