### ISSUE TITLE
Logger scope not set correctly for worker

### ISSUE THREAD

**Issue by jcapcik** [graphile/worker#418]
### Summary

Out of the box, the default log output does not include the `jobId` or `workerId`.  When following the example of how to write your own logger function, the `scope` property does not match what is defined - it has a nested `scope` property where `workerId` is.

### Steps to reproduce

```
function logFactory(scope) {
  return (level, message, meta) => {
    console.log('scope', scope)
  }
}

const logger = new Logger(logFactory)

const runner = await run({
  logger,
})
```

### Expected results

```
scope {
  label: 'job',
  taskIdentifier: 'test',
  jobId: '1',
  workerId: 'worker-56079d283d5b73e90f'
}
```

### Actual results

```
scope {
  scope: { label: 'worker', workerId: 'worker-56079d283d5b73e90f' },
  label: 'job',
  taskIdentifier: 'test',
  jobId: '1'
}
```

### Possible Solution

It looks like this commit changed how the worker set the scope, and the nested scope property just needs to be removed?:
https://github.com/graphile/worker/commit/3563980e98f2e2c1bbf7508ba1f323c85d0ec9dd#diff-1245a5bbc4ca0684dff978efcae118b08f62d2afc05812df22d0627985b4273aR43

**Comment by benjie** [comment]
Released in v0.16.2
