### ISSUE TITLE
Documentation: detail how to pass a preset to `run()`

### ISSUE THREAD

**Issue by benjie** [graphile/worker#453]
```ts
import type {} from "graphile-config";
import { run } from "graphile-worker";
import { WorkerProPreset } from "@graphile-pro/worker";

const preset: GraphileConfig.Preset = {
  extends: [WorkerProPreset],
  worker: {
    /* Your worker config options here */
    connectionString: process.env.DATABASE_URL,
    maxPoolSize: 10,
    // ...
  },
};

const promise = run({ preset });
```

This needs detailing both on the library page and the worker pro page.

**Comment by jcgsville** [comment]
Just stumbled over this, and it took me a couple minutes to figure this out. Are you open to me adding it to the docs, or do you want to save it for another contributor for their first issue?

**Comment by benjie** [comment]
Please have at it! Presets are very new in Worker, there's a lot more to be done with their integration (and the deprecation of the non-preset version). I'm trying to standardize the Graphile suite around Graphile Config so that all of our software uses similar patterns for plugins, presets, middleware, hooks, etc - but Graphile Config itself is currently incredibly poorly documented because it's part of the PostGraphile V5 system and is itself still being iterated.

**Comment by jcgsville** [comment]
Coolio. Happy to also take a stab at improving the documentation for Graphile Config, though it sounds like that may want to wait until it's more stable?

(I'm viewing doing a pass on documentation as a good way to understand more deeply how these things work with the goal of enabling both ongoing contribution and better understanding for my future usage of graphile stuff)

**Comment by benjie** [comment]
It’s got quite wide usage already, so documenting the commonly used parts at least would be wise. I think Graphile config needs two docs: one for library authors/plugin authors, and one for regular consumers.
