### ISSUE TITLE
Environment variable changes not reflecting in jobs

### ISSUE THREAD

**Issue by alexghattas** [graphile/worker#456]
NodeJS 20 - Express with Typescript
PostgreSQL: 15.1.0.103
Hosted with Dokku (Heroku OS)
Graphile-worker version: 0.16.1

**The issue:**
When I update an environment variable in my remote environments (i.e. staging), the changes are not reflected in the code when it is used by the queue system (i.e. the code is being run by graphile-worker is still using the old env variable values).

**Context:**
We use graphile-worker to download and merge multiple files for our users, we updated the S3 region to use a new bucket, and these details are stored in an env variable. When I download a file not using the queue, it works as expected. When I go to download the files that uses the queue system, it is still referencing the old env variables.

I have redeployed my app a few times, which restarts the graphile-worker, but the issue persists.

Has anyone experienced this before?

Thank you!

**Comment by benjie** [comment]
Hi Alex; Worker has no caching of environmental variables, so this is not a bug in worker.

Are you using a bundler (webpack or similar) which might be hardcoding the envvars at the time of build into your bundle?

Alternatively, are you using a runner like pm2 which caches the environmental variables that were used when the process was first started, and doesn't reflect changes?

Alternatively, are you actually not restarting worker even though you think you are?

**Comment by benjie** [comment]
No idea; sorry! I suggest that you log the envvars inside the `startGraphileWorker` function (e.g. where you do `Graphile Worker started`) - that should make it clear if the envvars are wrong in your script and not just inside Graphile Worker.

**Comment by benjie** [comment]
Note your worker usage is wrong; you need to await `runner.promise`; see: https://worker.graphile.org/docs/library#add-the-worker-to-your-project
