### ISSUE TITLE
Next job (getJob) returns nondeterministic results

### ISSUE THREAD

**Issue by nnaku** [graphile/worker#457]
### Summary

Workers next job that will be executed is not deterministic in case when multiple job's has same `priority` and `run_at`. This happens, for example, when multiple job's are added during the same transaction because `run_at` timestamp defaults to `now()` which is transaction timestamp. Therefore the next job that will be executed is seemingly more or less random if jobs are added in same transaction. 

Im not even sure if this is a bug, but usually it's nice to have deterministic result!

### Steps to reproduce

Add multiple jobs through the SQL interface with in same transaction. 

### Expected results

First in, first out if everything else are equal.

### Actual results

Next job depends on PostgreSQL internal implementation details.

### Possible Solution

I guess that `_private_jobs.id` is sequence and it could be used as a last ordering rule?

**Comment by benjie** [comment]
I attempted adding `id` to the `ORDER BY` and it reduced worker performance by a factor of 3.

Determinism isn't an aim of the queue in this situation, but if you really need determinism consider being more explicit with your `run_at`; timestamps in postgres support 6 decimal places on seconds, and you can use `clock_timestamp()` to get the current timestamp (as opposed to `now()` which never changes within a transaction).

**Comment by nnaku** [comment]
Did you update the index also? I toyed around pref test and got quite similar result before updating the `jobs_main_index`  index.  https://github.com/nnaku/worker/commit/7b651d79fc40b90995c7ce36c466d27d43056e9f

**Comment by benjie** [comment]
I did not, it’s an interesting idea but it would increase the size of the index which has a (small) impact on write performance and to my mind if you have the same priority and run_at then whichever the DB reads first is fine, further ordering is unnecessary. Determinism in all situations is not a goal, and is achievable in most situations via carefully setting run_at.
