### ISSUE TITLE
Why this library depends on uuid-ossp?

### ISSUE THREAD

**Issue by testarossaaaaa** [graphile/worker#47]
I only found use of the gen_random_uuid() function, but it comes from pgcrypto, no one from uuid-ossp, maybe uuid-ossp is a rudiment? Also, uuid-ossp does not provide the uuid type because it is already built-in.

**Comment by benjie** [comment]
Maybe it doesn't need it; try removing it from the three places it's mentioned and if the tests still pass it's probably fine to merge :+1:

**Comment by testarossaaaaa** [comment]
Yes, all tests passed.
