### ISSUE TITLE
concurrentJobs is ignored in graphile.config.js

### ISSUE THREAD

**Issue by ThHareau** [graphile/worker#471]
### Summary

It seems like  `concurrentJobs` options is ignored in the config file. 1 is used instead. 

### Steps to reproduce

* `git clone git@github.com:ThHareau/graphile-ignored-config-options.git`

#### Setup phase
* `psql postgres://postgres:postgrespassword@localhost:5432 -c "CREATE DATABASE concurrent_jobs_options;"`
* `npm run worker -- --once` to run migrations

#### Enqueue jobs

* `psql postgres://postgres:postgrespassword@localhost:5432/concurrent_jobs_options -c "SELECT graphile_worker.add_job('slow_job');"`
* `psql postgres://postgres:postgrespassword@localhost:5432/concurrent_jobs_options -c "SELECT graphile_worker.add_job('slow_job');"`

#### Bug

* `npm run worker -- --once`

### Expected results

Both jobs should be launched in parallel: 

```
[core] INFO: Failed to read crontab file '/home/thareau/Documents/Projects/tests/graphile-test-config/crontab'; cron is disabled
[job(worker-9d31dbf892cb7f520b: slow_job{3})] INFO: Starting job
[job(worker-56026b696dfbf9a911: slow_job{4})] INFO: Starting job
[job(worker-9d31dbf892cb7f520b: slow_job{3})] INFO: Done
[worker(worker-9d31dbf892cb7f520b)] INFO: Completed task 3 (slow_job, 2002.76ms) with success
[job(worker-56026b696dfbf9a911: slow_job{4})] INFO: Done
[worker(worker-56026b696dfbf9a911)] INFO: Completed task 4 (slow_job, 2000.95ms) with success
```

(this can be achieved by running the same setup and then `npm run worker -- --once -j 2 -m 2`

### Actual results

Both jobs are run sequentially : 

```
[job(worker-a5cf51c8321e2d0a8a: slow_job{1})] INFO: Starting job
[job(worker-a5cf51c8321e2d0a8a: slow_job{1})] INFO: Done
[worker(worker-a5cf51c8321e2d0a8a)] INFO: Completed task 1 (slow_job, 2002.04ms) with success
[job(worker-a5cf51c8321e2d0a8a: slow_job{2})] INFO: Starting job
[job(worker-a5cf51c8321e2d0a8a: slow_job{2})] INFO: Done
[worker(worker-a5cf51c8321e2d0a8a)] INFO: Completed task 2 (slow_job, 2002.41ms) with success
```

**Comment by benjie** [comment]
From Discord:

> Yeah; it's almost certainly caused by https://github.com/graphile/worker/blob/a2ba675833b0fc9538328ba5a91e1165e235395a/src/cli.ts#L48
> Want to delete that line and see if it fixes the issue?
> Specifically we need it to be `undefined` here: https://github.com/graphile/worker/blob/a2ba675833b0fc9538328ba5a91e1165e235395a/src/cli.ts#L105
> Any of the `integerOrUndefined` settings shouldn't have a default IIRC.
