### ISSUE TITLE
Task specific event handler

### ISSUE THREAD

**Issue by wong2** [graphile/worker#482]
### Feature description

Allow users to define event handler in task files, instead of the global `events` configuration. Only events related to this task will be dispatched to it.

### Motivating example

I need to update the database record when a task fails (after all the retry attempts). Currently, I have to do it in the global `events` configuration like this:

```
const events: WorkerEvents = new EventEmitter()

events.on('job:failed', ({ job }) => {
  if (job.task_identifier === 'send-email') {
    const userId = job.payload.userId
    await db.update(...)
  }
})

const preset: GraphileConfig.Preset = {
  worker: {
    events,
    ...
  }
}
```

Instead, I want to place the code with the task executor code, so I can reuse the imports, types, functions etc.

### Supporting development

- [ ] am interested in building this feature myself
- [ ] am interested in collaborating on building this feature
- [x] am willing to help testing this feature before it's released
- [ ] am willing to write a test-driven test suite for this feature (before it exists)
- [ ] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by benjie** [comment]
You should wrap your talk executor in atry/catch with the catch doing `if (helpers.job.attempts >= 20) {await cleanup()} else {throw err}`

This way the cleanup itself will be retried on failure AND the permafailed job won’t stick around in your queue making everything slow.

**Comment by wong2** [comment]
@benjie Thanks, I will try this method

**Comment by benjie** [comment]
Since the existing method works fine and I think you could build a system on top of Worker to do what you describe without it needing to be natively supported by worker, I'm going to close this for now.
