### ISSUE TITLE
Error relation "graphile_worker.known_crontabs" does not exist

### ISSUE THREAD

**Issue by pastushenkoy** [graphile/worker#485]
### Summary

After updating to `0.16.6` we constantly see the following error in our Postgres logs: 
```
2024-08-19 13:52:43.362 UTC [4040] ERROR:  relation "graphile_worker.known_crontabs" does not exist at character 15
2024-08-19 13:52:43.362 UTC [4040] STATEMENT:  SELECT * FROM "graphile_worker".known_crontabs
```

Seems like it doesn't affect any graphile worker's functionality. We don't use graphile worker's crons though.

### Steps to reproduce

I believe, just using version `0.16.6` should be enough. Seems like there's not view or table with the name. It used to be, but now it's [renamed](https://github.com/graphile/worker/blob/main/sql/000016.sql#L5C37-L5C51). 

### Expected results

Expecting no error.

### Actual results

Seeing error.

**Comment by benjie** [comment]
Indeed; these two lines do look rather suspicious:

https://github.com/graphile/worker/blob/5650fbc4406fa3ce197b2ab582e08fd20974e50c/src/cron.ts#L145-L146

**Comment by benjie** [comment]
I could not reproduce this issue, nor track it down in the code. The query your logs report is quite explicit; it seems to come from this line:

https://github.com/graphile/worker/blob/v0.15.1/src/cron.ts#L176

But that was removed in v0.16.0; as you can see the statement is changed here:

https://github.com/graphile/worker/blob/v0.16.6/src/cron.ts#L185

So my guess is that you have an old version of worker still running against your database, hence the errors. [Worker Pro](https://worker.graphile.org/docs/pro/migration) can help you avoid this kind of issue.
