### ISSUE TITLE
Support for standard PG environment variables

### ISSUE THREAD

**Issue by garcianavalon** [graphile/worker#50]
Opened as continuation of #45 to propose an actual implementation.

### Rationale
Postgres tooling, for example psql, uses [these environment variables](https://www.postgresql.org/docs/9.3/libpq-envars.html) defined in `libpq` to connect to the database. AFAIK, this is the standard way to configure applications on different environments. In my particular case, I use these variables in my Postgraphile-powered backend to behave differently in local, dev or production environments.

The underlying library, pg-node, also [supports these variables for connection](https://node-postgres.com/features/connecting). One convenience is that these library [automatically detects when using UNIX Sockets based on the host string](https://node-postgres.com/features/connecting#Programmatic%20Connection%20to%20Sockets), and builds the connection string accordingly. In my particular case, I make use of these feature using postgraphile: when running locally I use HTTP sockets, when running on the cloud (GCP App Engine) I use UNIX sockets.

To configure graphile worker, I've had to add extra logic to build a full  database connection url. Simplified version:
```js
// this pgConfig is used to configure postgraphile also
const pgConfig = { 
  user: process.env.PGUSER || 'postgres',
  host: process.env.PGHOST || 'localhost',
  database: process.env.PGDATABASE || 'myuser',
  password: process.env.PGPASSWORD || 'mypassword',
  port: process.env.PGPORT || 5432
}
// this connection string is used to configure graphile worker
let connectionString
    if (process.env.DB_USE_UNIX_SOCKETS) { // or logic based on host
      connectionString = `postgres+pg8000://${pgConfig.user}:${pgConfig.password}@/${pgConfig.database}?unix_sock=${pgConfig.host}/.s.PGSQL.${pgConfig.port}`
    } else {
      connectionString = `postgres://${pgConfig.user}:${pgConfig.password}@${pgConfig.host}:${pgConfig.port}/${pgConfig.database}`
    }
```

I feel this is redudant with pg_node features and should be handled by that library.

### Current Behaviour
Current implementation of graphile woker fails to use this variables (seems to only support a `DATABASEURL` variable)

From CLI
```
Error: Please use `--connection` flag or set `DATABASE_URL` envvar to indicate the PostgreSQL connection string.
    at main (/Users/garcianavalon/Development/api-monolith/node_modules/graphile-worker/dist/cli.js:67:15)
    at Object.<anonymous> (/Users/garcianavalon/Development/api-monolith/node_modules/graphile-worker/dist/cli.js:98:1)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at findNodeScript.then.existing (/usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)
```
As library 

```
Error: You must either specify `pgPool` or `connectionString`, or you must make the `DATABASE_URL` environmental variable available.
    at assertPool (/Users/garcianavalon/Development/api-monolith/node_modules/graphile-worker/dist/runner.js:41:15)
    at withReleasers (/Users/garcianavalon/Development/api-monolith/node_modules/graphile-worker/dist/runner.js:80:30)
(node:84111) UnhandledPromiseRejectionWarning: Error: Fatal error starting runner %s
    at module.exports.startRunner (/Users/garcianavalon/Development/api-monolith/src/runner.js:26:11)
(node:84111) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

### Proposed solution
My first proposed solution is to maintain the same API as postgraphile and accept the pgConfig object. This is not a viable solution (check #45)

The proposed solution would be to not fail if `DATABASE_URL` is not found and delegate to pg_node to parse the `PG*` env variables to build the correct connection string. This would be a DRY approach that avoids adding more logic (both in graphile and in our applications) and following standard pg configuration.

**Comment by benjie** [comment]
We need to perform at least _some_ validation. So how about we add `PGDATABASE` to the list of options; so you provide either `--connection`, `process.env.DATABASE_URL` or `process.env.PGDATABASE`? On macOS `node-postgres` seems to default `PGHOST` to allowing sockets, whereas on Linux `node-postgres` defaults `PGHOST` to localhost requiring a TCP connection... maybe we should require both `PGHOST` and `PGDATABASE`?

The main thing I want to avoid is having to spend loads of time supporting people who cannot get it to work because they believe they've told it how to connect but they haven't, so I definitely don't want to just pass through to `node-postgres` without some form of validation.

**Comment by madflow** [comment]
> As library

> Error: You must either specify `pgPool` or `connectionString`, or you must make the `DAT

Using a `pgPool` already works with the standard Postgres environment variables.  Adding more options to the cli/Runner Options would add extra noise that I personally would not need. Just another opinion here...

**Comment by garcianavalon** [comment]
I see, so the pain point is users requesting support here instead of reading `node-postgres` docs 😅 

I would say lets check for `PGHOST` and `PGDATABASE`. Maybe point to `node-postgres` docs on the error message?

Also, removing `pgOptions` in PostGraphile 5 to standarise APIs would be great (another discussion though)

**Comment by benjie** [comment]
If I can throw out the duck-typing in PostGraphile v5 I'll be very pleased!

Implementation-wise I think this issue just requires us to change when/if errors are thrown and the error texts; as you said pg.Pool should pull in the relevant settings automatically.

**Comment by benjie** [comment]
@garcianavalon @lukeramsden @madflow Would you mind taking #139 for a spin and see if it meets your needs?

**Comment by garcianavalon** [comment]
It looks good! I'll update the worker as soon as posible and try it out. Thanks @benjie !

**Comment by benjie** [comment]
It's `yarn add graphile-worker@next` right now (or use the version number explicitly).
