### ISSUE TITLE
Question: recommended approach for handling thousands of jobs?

### ISSUE THREAD

**Issue by nullpaper** [graphile/worker#504]
### Summary

This question is about the specific case of sending out a series of newsletters to 10k+ recipients at a time (though the question gets spicier if you bump that number up by 10-100x). 

What is the recommended approach (for a NodeJS Typescript project) to handle batches of 10k+ tasks? 

### Additional context

ONE JOB PER EMAIL
Starting with the assumption that we want one small "send" job for each email, we'd ideally be looking at inserting 10k+ job rows for our newletter send, either:

- **Iterating over `addJob()`**: this seems crazy for 10k+ as it's so inefficient. It "works" but it's brittle (failed write potential) and  slow.
- **Using SQL `graphile_worker.add_jobs()`**: for the life of me I can't get this to work (cast correctly - have tried with json, records, and multiple different attempts to cast `graphile_worker.job_spec`). But even if this can work, it'll still need raw SQL instantiation correct, as there's no library API for this yet? Nonethless, this "seems" like it might be the canonical approach to inserting large numbers of jobs. But it's also a bit opaque - what's going on behind the scenes, how is it writing, what happens on fails, etc.
- **Raw write to `_private_jobs`**: I know, I know. But this approach _works_, and I can use standard SQL batching techniques to write to this table, all wrapped up in transactions. Outside schema change risks, does this approach negatively impact graphile worker in other ways?

ONE JOB PER NEWSLETTER
The alternative would be to batch (and put the 10-100k send ids in a payload array). But this would seem to violate the "keep your jobs small" as we'd have to sit and wait for all those tens of thousands (or more) of promises to resolve. Even still, maybe that IS the canonical way to approach this?

---

The specific number in the batch of tasks here is less important than the underlying question regarding how to approach this "batch" job use-case. Would love a steer here. Right now I'm leaning into "raw write to _private_jobs" which is clearly not canon.

**Comment by benjie** [comment]
Adding add_jobs to the JS API has been on my TODO list for a while. Graphile Worker was originally designed to be triggered from database code (DB functions, triggers, etc), so the JS interface for adding tasks is often secondary. Here's how you can call the add_jobs function:

https://github.com/graphile/worker/blob/3e6b8700206eb33045105ab7aec811ef1f6e0379/__tests__/runner.helpers.getTaskName.test.ts#L65-L81

It's definitely understandable that you didn't come up with that on your own, looks like it may have taken me a couple attempts!

---

Separately about the approach. This is a problem I've had to solve before; so here's how I'd do it:

1. I file a single job to trigger the sending-out of this newsletter
2. That `send_newsletter` job splits the required work into batches of 1000-10000 emails or so, and files a job for each batch (which should use add_jobs()) passing the userIDs or similar as part of the payload
3. That `send_newsletter_to_user_ids` job then batch fetches these 1000-10000 user accounts and performs the templating/mailmerge for them, and then creates jobs for sending each individual email (via `add_jobs()`)
4. The final `send_email` job is responsible for sending exactly one email to exactly one person, and the automatic retries is helpful here. It's also a generic job that I'd use from various other parts of my app too, it's not specific to sending a newsletter.

Whilst sending emails I would spin up a lot more workers, which would churn through them a lot faster, then I'd scale back down again. You don't have to do this, but it can easily change the duration of the send from hours to minutes if you're sending hundreds of thousands of emails. May also depend on the rate limits of your email sending provider.

The above wasn't with Graphile Worker (it was a previous job queue I wrote in Ruby, many years ago); but I'd do it the same way in Worker.

**Comment by nullpaper** [comment]
Super helpful reply @benjie thank you 🙏  
I'll close this ticket off, hopefully it'll help others looking for `add_jobs()` syntax.
