### ISSUE TITLE
Some params defined in custom config are not picked up by graphile-worker CLI

### ISSUE THREAD

**Issue by mieszko4** [graphile/worker#511]
### Summary

Some params defined in custom config are not picked up when running `graphile-worker` CLI.
For example `schema`.

### Steps to reproduce

Use custom config with custom schema:
*custom.config.js*
```js
const preset = {
  worker: { schema: "my_schema" },
}

export default preset
```

Then run:
```sh
./node_modules/.bin/graphile-worker --config custom.config.js
```

### Expected results

Uses `my_schema` schema.

### Actual results

Uses `graphile_worker` schema (default).

### Additional context

When resolving config in CLI, the config is extended with args (with most priority). There is `stripUndefined` but it does not work for args which have default value defined.

### Possible Solution

Adjust resolving config so that it does not override with default arg value if it was indeed not provided as CLI arg.
 

Work around is to provide `--schema` in CLI:
```sh
./node_modules/.bin/graphile-worker --config custom.config.js --schema my_schema
```

**Comment by benjie** [comment]
Fixed in:

- https://github.com/graphile/worker/pull/473
