### ISSUE TITLE
Add an option to default to forceful shutdown

### ISSUE THREAD

**Issue by antonioorct** [graphile/worker#526]
### Feature description

In production my current setup is that the app scales up and down and on scaling down it doesn't shut down gracefully, I'm not 100% sure about the scale-down process, it sends a SIGTERM signal but I think it then just kills the process. In any case it doesn't allow jobs to finish and leaves them locked and they aren't unlocked until 4 hours later which for my use case is too long.

Also in development my app force shuts down after 5 seconds of a SIGTERM signal. This leads to unfinished and locked jobs 99% of the time and thus requires me to delete the job and re-add it manually.

I'd like to have an option when the runner receives a SIGTERM signal to instantly abort all jobs and unlock them. This way the other instances can pick up the work. I'm not too concerned about cancelled jobs as they can just restart and pick up where they left off.

### Motivating example

See above.

### Supporting development

I [tick all that apply]:

- [ ] am interested in building this feature myself
- [ ] am interested in collaborating on building this feature
- [ ] am willing to help testing this feature before it's released
- [ ] am willing to write a test-driven test suite for this feature (before it exists)
- [ ] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by benjie** [comment]
I'm not keen to add that as an option; but here's a plugin I've written for you that triggers a forceful shutdown 500ms after a graceful shutdown starts:

```ts
// graphile.config.ts

const ForceShutdownPlugin: GraphileConfig.Plugin = {
  name: "ForceShutdownPlugin",
  worker: {
    hooks: {
      init({ events }) {
        events.on("pool:gracefulShutdown", ({ workerPool }) =>
          setTimeout(() => workerPool.forcefulShutdown("Abandon ship!"), 500),
        );
      },
    },
  },
};

const preset: GraphileConfig.Preset = {
  plugins: [ForceShutdownPlugin],
};

export default preset;
```

If you find this helpful, please consider supporting my work through [GitHub Sponsors](https://github.com/sponsors/benjie); every contribution helps me to put more time into open source and helping users like you. Thanks!
