### ISSUE TITLE
addJob - helper function

### ISSUE THREAD

**Issue by panthershark** [graphile/worker#55]
I'm using this as lightweight event bus. There are a bunch of places in my platform where events need to be produced from random code blocks. The intent of this library appears to be queue messages from db triggers, but in my case there is no db corresponding db write and synthesizing one seems hamfisted. 

Currently, the addJob function is attached to the runner instance. It's be cool if the addJob function was exported separately that either generate the query and the call params or take a db connection and run the insert. The reason for the connection and not a pool is that cloud functions dont do well with pools and people might want to queue messages from webhooks or something.

The main argument for exporting this and having it travel with this library is that if the db schema changes or something, it would also get updated.

If you are open to it, I'll do the work.  Would you accept a PR that exports the addJob function standalone? 

If not, this is no big deal. It is easy to queue with the sproc. Thank you for making this lib. :)

**Comment by benjie** [comment]
Yes; I totally intended to add this API at some point. We already have the `makeAddJob` function; we just need to export a wrapper around this at the root level I think? I suggest that you write the README changes explaining what the new API is first, we can discuss that, and then when we've reached concensus you can go ahead and write the underlying code if you want :+1: 

I'd also like to make it so you can add a job from the CLI; something like:

```
graphile-worker add-job happy_new_year --payload='{"fullYear":2020}' --queue=queue_name --maxAttempts=3 --runAt=2020-01-01T00:00:00Z
```

I suspect there will be significant overlap between these two use cases.
