### ISSUE TITLE
[Discussion] Let TS users overload `addJob`

### ISSUE THREAD

**Issue by keithlayne** [graphile/worker#56]
I see two different options for doing this, and there are tradeoffs for each.  Wanted to lay those out here before implementing (none entail much work, and I don't *think* any would be breaking changes):

*NOTE:* For any of these to work (assuming they are in `interfaces.ts`, the interface being augmented should to be exported by name from the top level.

### Option 1: Change `AddJobFunction` to an interface with a call signature

Changes:
```ts
export interface AddJobFunction {
  (identifier: string, payload?: any, options?: TaskOptions): Promise<Job>;
}
```
Adding an overload:
```ts
import { Job, TaskOptions } from 'graphile-worker'

declare module 'graphile-worker' {
 interface AddJobFunction {
    (identifier: 'taskName', payload: Payload, options?: TaskOptions): Promise<Job>
  }
}
```
Special TS rules bump this overload to the top of the list due the non-union literal.

Pros:
* Users can't screw it up at call sites

Cons:
* Verbose
* Have to import extra types

### Option 2: Generic overload with a type map

Changes:
```ts
export interface TaskPayload {}
export interface AddJobFunction {
  <T extends keyof TaskPayload>(identifier: T, payload: TaskPayload[T], options?: TaskOptions): Promise<Job>
  (identifier: string, payload?: any, options?: TaskOptions): Promise<Job>;
}
```
Adding an overload:
```ts
declare module 'graphile-worker' {
 interface TaskPayload {
    taskName: Payload
  }
}
```

Pros:
* Easier to add an "overload"

Cons:
* Users can pass the type param explicitly or pass something other than a string literal as the task name; this could cause bogus inputs to type check

I had another idea that actually won't work because the payload is required in (at least most) overload signatures and not in the default signature.

I started writing this favoring option 2, but at this point I feel like correctness trumps brevity.  They're both easy to implement, so whatever is decided here can be turned around quickly.

**Comment by keithlayne** [comment]
The limitation on the second option could probably be overcome with some kind of `NonUnion` type.  Not sure if that's worth it, but I do like the improved ergonomics of that option.

**Comment by keithlayne** [comment]
Here's an [example](https://www.typescriptlang.org/play/index.html?ssl=28&ssc=17&pln=27&pc=1#code/C4TwDgpgBAqgdgSwPZwCpIJJ2BATgZwgGNhk4AeGAPigF4oAoKKAChiggA8c4ATfKAEM4IKAH5WAawBcsAJR0aANyQJeUWXAhK8Crj36sWMqAjgAzPFAwLay1bwUSMGqFp24mjMzlznBRNCogviSAAqCIAA2SILqAN5e5khImgCuALYARngMAL4MDD54-oFQAIK8vABSSFkAYmlwJGRQiczkqBzcEHwCkhAgSOZQwaER0bG8VCxqvaTmCHiyqAA0UGCRMXErIeFbUwDa8GToWL6ELSidNABkUANDI2P7k3EAunKyKmpes7zzBCLZZQfDAXBmADm602b14YlkwhAXygP14+UKAKIUUEuGgRBQYKEVVqWVklRqdUazVIKAYWJxeKgBLgRPBSDSWSiEFkAHJkkheVAAD5QXlZXG8wrFPwBIJ7CbbBJeCW4WRgiFwSEYhhxSlZFj8lK89YARgUAHoLcyUlFdSS6oaBSaxXAkMAhG5MjlcLzLdb-FEogIJURJFBgEhQeCocwkB4lRoWPb9eQjYKZumXby3R7BF7sng-VArd0wFEEEQEB7NrhBBkoMlcIEBNWI1GwJXw5DenhK1B43glSnSSx2Zzuesc+7PXBvUX-dHNZCBwmpkmR3U086RWLVbzM86p7nZ-PfYu8LgkJ49aOs8eZ-m54XzyXrZ2wwINbHB7hE9Jk1vR0s0XAB3DkonUPFBCDUQKwGCMAAsEAESNG0EBAog3IA) for an improved(ish) option 2.  Unfortunately, I just keep on finding ways to break it.

**Comment by keithlayne** [comment]
Or...probably could augment  `Helpers` directly.  I was trying to  figure out a better UX around it, I will have to try it out.  Something like `interface Helpers extends AddJobOverload<'taskName', Payload {}`.  Just have to see if a) it does the right thing w.r.t. overload ordering  b) anyone likes that.

**Comment by benjie** [comment]
One thing we should keep in mind is that the payload may not be a concrete type but a union itself; e.g. we might have a task called 'generate_report' and file jobs against it like `{type:"year_end", year:2019}` or `{type: "productivity", department: "sales"}` or `{type: "summary", year: true, month: true, day: false}`. We may also have versioned payloads that evolve over time. We may also have the situation where the code in the database queues an invalid job that breaks the types, so trusting the types may not be safe.

I think showing people how to spec and validate their tasks using something like `runtypes` might be a better approach. Then you can use `if (isV1YearEndPayload(payload)) { const {type, year} = payload; ...} else if ...`.

**Comment by keithlayne** [comment]
I don't see a fundamental issue with union payloads in overloads.  You'd almost definitely want to represent it as a union in an overload instead of multiple overloads with the same task name, but it doesn't really change anything.

I in fact am using runtypes on my end, and using it to generate the payload type I add to the overload as well as validate payloads to tasks, so there is a single source of truth in my case.

I've written a task wrapper around this that abstracts payload validation with runtypes and allows you to write handlers with typed inputs.  I've found it pretty handy, and would like to share, but don't really know where to do so.

**Comment by keithlayne** [comment]
Just to be clear, in the case you describe I'd make a top-level payload runtype as a union of the different versioned types.  Although it might make more sense to do something else in some cases.  Leveraging runtype's pseudo-pattern-matching stuff could be very handy there.

**Comment by keithlayne** [comment]
Also to be clear, the role of i.e. runtypes here is purely validation in task definitions - overloading `addJob` is just about getting type checking on that function as an extra layer of safety at call sites.  I didn't mean to imply that this would in any way replace payload validation in tasks - in my case, relatively few tasks will be enqueued from JS/TS, and I know the overloads only help with that.
