### ISSUE TITLE
Cancel/modify delayed jobs

### ISSUE THREAD

**Issue by gregplaysguitar** [graphile/worker#58]
I'm exploring a case where I need to be able to somehow cancel or modify jobs in the graphile worker queue which have been delayed using the `run_at` argument. Looking at the source, it seems this would be trivial to achieve by deleting from `jobs` by id, but because the id is a serial, I would need to store it somewhere. If the id could be pre-generated (as a uuid4 or something similar) and passed to the `add_job` function, then I could generate the same id again in order to delete or update the job. So the changes would be 

- use a uuid for the jobs primary key instead of bigserial
- default it to `gen_random_uuid` but allow the id to be provided as an optional argument to `add_job`

Is there some reason I haven't considered, why this would be a bad idea? I'm assuming the insert performance would be better if the sequence was removed, but unsure how it would impact reads from the job table.

**Comment by benjie** [comment]
For future readers, a solution has been proposed and is being discussed in #61.
