### ISSUE TITLE
Is task de-duplication supported?

### ISSUE THREAD

**Issue by beepsoft** [graphile/worker#67]
Hi,

I really like the idea of a postgresql based job queue and graphile worker in particular.

My only concern is whether there is a way to prevent the same task to be added to the queue twice (by multiple parallel processes somehow wanting to schedule the very same task). 

In Google Cloud Tasks de-duplication is supported by allowing the task creator to specify an ID for the task. 

Can a similar behaviour somehow be achieved in graphile worker? 

One solution I could see is adding a unique index on the job payload like this:

```
CREATE UNIQUE INDEX unique_payload ON table graphile_worker.jobs(payload);
```

Then the task creator would be responsible to include a UUID or some other data that makes each task payload unique and the unique index would make a job addition fail if the same was added twice.

Is this solution feasible or is there some better way to do this?

**Comment by benjie** [comment]
This is now built in. In 0.3.0-rc.0 (`graphile-worker@rc`) we merged #63 which adds a job_key. This can be used to update an existing job rather than enqueuing a new one, in effect de-duplicating. You can read more about this in the README:

https://github.com/graphile/worker#updating-and-removing-jobs

**Comment by beepsoft** [comment]
Oh, there's a `job_key` now, great!

Thank you!

**Comment by benjie** [comment]
You’re welcome; and thanks to @gregplaysguitar for pushing for this feature and for implementing it. Let us know how you get on with the release candidate, it’s nice to have some confirmations before it goes on general release 👍

**Comment by benjie** [comment]
I've tweaked the README to make this feature clearer: https://github.com/graphile/worker/commit/afca37478f27c430d0a7e1a279ce8f710c6c55a2
