### ISSUE TITLE
Add examples of using worker to send tasks to other queues

### ISSUE THREAD

**Issue by benjie** [graphile/worker#7]
- [x] Faktory
- [ ] SQS
- [ ] RabbitMQ
- [x] GCP Cloud Tasks

**Comment by madflow** [comment]
Where would these examples go? 

* [ ] Wiki
* [ ] Readme
* [ ] /examples

I have used a similar approach to export database events to https://github.com/contribsys/faktory in the past. So this could be an example...

**Comment by benjie** [comment]
Lets go with `/examples` for now 👍

**Comment by garcianavalon** [comment]
I would send an example on how to delegate to GCP Cloud Tasks

**Comment by benjie** [comment]
Awesome :raised_hands:  Follow the pattern set out by [the faktory example](https://github.com/graphile/worker/tree/master/examples/worker-faktory-exporter) please :+1:

**Comment by garcianavalon** [comment]
PR open @benjie

**Comment by keithlayne** [comment]
I can do SQS if nobody has before I get to it.  Wrote SQS->worker code today in my project, will do the other direction soon.

**Comment by benjie** [comment]
Yes please @keithlayne :raised_hands:

**Comment by benjie** [comment]
(Also if you want to show an SQS -> worker example too, that'd also be welcome!)

**Comment by benjie** [comment]
Closing this; I'm happy with what we have.
