### ISSUE TITLE
Make an official Docker image

### ISSUE THREAD

**Issue by benjie** [graphile/worker#85]
Preferably with instructions about how to add your tasks.

**Comment by keepitsimple** [comment]
Hi @benjie. Can I make a PR with small polishing for the docker & docker compose?

**Comment by benjie** [comment]
That’d be ace 👍

**Comment by keepitsimple** [comment]
@benjie I cannot push a new branch and make a PR. Can you advice please?

**Comment by benjie** [comment]
Please fork the repo and make a PR from there; see: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

You can use your existing clone to do so; after you've created your fork you should use `git remote` to update your remote's URL; e.g.:

```
git remote set-url origin git@github.com:keepitsimple/worker.git
```

then you can `git push` and raise a PR from the GitHub interface on your fork.

**Comment by benjie** [comment]
Hey @keepitsimple how's it going?

**Comment by benjie** [comment]
This was implemented in https://github.com/graphile/worker/pull/111
