### ISSUE TITLE
inconsistent job table columns

### ISSUE THREAD

**Issue by stlbucket** [graphile/worker#86]
installing via:

```
npx graphile-worker -c $DB_CONNECTION_STRING --schema-only
```
there is no locked at or locked_at or locked_by

![image](https://user-images.githubusercontent.com/2467892/75207224-f9d6c180-572c-11ea-9f51-0edcf3c1d0a2.png)

but after adding a job, they appear

![image](https://user-images.githubusercontent.com/2467892/75207325-37d3e580-572d-11ea-8df1-8472ff34fb8b.png)

this causes me an issue when querying via graphql the exposed schema

**Comment by stlbucket** [comment]
more info:  if i call add_job directly, the field aren't added

if i add a job via makeWorkerUtils, the fields are added

**Comment by benjie** [comment]
It looks like you’re running an older worker and a newer worker. Running `graphile-worker --schema-only` with 0.4.0 should update you to the latest schema. Try and ensure everything in your stack runs the same version of worker.

**Comment by stlbucket** [comment]
to be clear - i'm using graphile-worker 0.4.0.   but i just used npx to initially install it because i was using a bash script to build up a database.

i suppose i should not rely on the npx version?

**Comment by benjie** [comment]
Npx should be fine, it’ll run your local version if present or the latest version otherwise.
